### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by royr2** [WizardMac/ReadStat#1]
Hey Evan, 
I am very new to this but I was trying to compile the source using cygwin and I get errors like 
src/readstat_bits.c:1:0: error: The C parser does not support -dy, option ignored
cc1.exe: warning: unrecognized gcc debugging option: n
cc1.exe: warning: unrecognized gcc debugging option: m
cc1.exe: warning: unrecognized gcc debugging option: i
cc1.exe: warning: unrecognized gcc debugging option: c
cc1.exe: warning: unrecognized gcc debugging option: l
cc1.exe: warning: unrecognized gcc debugging option: i
cc1.exe: warning: unrecognized gcc debugging option: b

etc. 

I have attached an image with some more errors. I needed this for your ReadData module for Julia. Is it a gcc version issue?

Any help would be much appreciated.

thanks

![image](https://cloud.githubusercontent.com/assets/6601579/2927495/5f5be9ea-d76d-11e3-9a47-023930b52ffe.png)

**Comment by hadley** [comment]
@royr2 I think you'd best off consulting with a julia-C expert - it should be straightforward to bind this library from Julia.

**Comment by royr2** [comment]
Okay, I never realized this issue was open. Thanks Hadley. I'll close this issue.
