### ISSUE TITLE
Alternative to the callback interface?

### ISSUE THREAD

**Issue by davidanthoff** [WizardMac/ReadStat#103]
Feel free to just close right away :)

I'm wondering whether there is an alternative to the callback interface for reading available? One where the client "drives" things?

The reason I'm asking is that I'd like to add a julia iterator interface to ReadStat.jl that streams data from a file. But the iterator interface in julia is client driven, i.e. the client calls a ``next`` method and then expects to receive the next row.

I could of course build some buffer story, i.e. in each ``next`` call let all the callbacks for that row happen, buffer those values, then return from the ``next`` function back to the client, and only later have the C library do the next round of callbacks for the next row, but if there was some non-callback interface it would make things a lot easier, potentially.

So, this is not an ask to add this, just a question whether that exists maybe already in the codebase, just in a slightly less exposed way.

**Comment by evanmiller** [comment]
Hi @davidanthoff,

It's a reasonable request, but there's not support in the code base right now. I see a couple ways forward:

* A slow-and-hacky way forward would be to implement a "row offset" feature in addition to "row limit" (`readstat_set_row_limit`). Then your `next` function would set the row limit to 1, and increment the row offset until the whole file was parsed. Note that this would require re-parsing the metadata with each row, unless some kind of caching or metadata preservation is implemented.

* A more complete solution would expose (hypothetical) functions like `parse_metadata` and `parse_next_row`, perhaps re-implementing `parse_dta` etc as calls to these.

For the sake of API simplicity I would prefer to keep the callback interface intact, but I'm open to exposing incremental parsing functions if that enables more applications such as iterators.

**Comment by davidanthoff** [comment]
I think we probably shouldn't invest any time in option 1, as you say, it is a bit hacky and this is not a super urgent issue in any case. If option 2 would become available at some point, I would certainly use it! Having said that, it is not super high on my priority list, so probably best if you just decided whether this makes sense for other clients as well or not,

**Comment by evanmiller** [comment]
I'm going to go ahead and close this issue until there's sufficient demand for incremental parsing.
