### ISSUE TITLE
Member name in SAS xport file generated by write_xpt is hard coded to "DATASET" 

### ISSUE THREAD

**Issue by sasutils** [WizardMac/ReadStat#104]
There is no way to tell the xport_write_member_header_record function what member name to use for the SAS transport file that it generates. Instead is it generating a header record that has the member name hard coded as "DATASET".

The user should be able to specify the member name that they want their SAS dataset to have in the transport file.

**Comment by evanmiller** [comment]
Implemented as of https://github.com/WizardMac/ReadStat/commit/8e91c0dcbaf6a4ea79550eebb96632c277d62bea

```C
const char *readstat_get_table_name(readstat_metadata_t *metadata);
readstat_error_t readstat_writer_set_table_name(readstat_writer_t *writer, const char *table_name)
```
