### ISSUE TITLE
Use stdout not stderr upon successful conversion

### ISSUE THREAD

**Issue by kylebarron** [WizardMac/ReadStat#116]
This isn't a huge deal but it seems like ReadStat uses stderr for successful output.

After running (from Python)
```py
readstat = subprocess.run(
    ['readstat', 'file.dta', '/tmp/file.csv'],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE)
```
the value of `readstat` is
```py
CompletedProcess(
    args=['readstat', 'file.dta', '/tmp/file.csv'],
    returncode=0,
    stdout=b'',
    stderr=b'Converted 202 variables and 15899 rows in 0.88 seconds\n')
```
Can this package instead use stdout when the program ran successfully?

**Comment by evanmiller** [comment]
Done, thanks for the suggestion!

**Comment by kylebarron** [comment]
Thanks! Just FYI, I just tried to overwrite a file and the error came to stdout, not stderr. I don't mind this because the return code is still 1, but just letting you know in case you wanted to try to have all errors go to stderr.
```py
CompletedProcess(
    args=['readstat', 'file.dta', 'file.csv'], returncode=1,
    stdout=b'Error opening file.csv: File exists (Use -f to overwrite)\n', stderr=b'')
```

**Comment by evanmiller** [comment]
Thanks
