### ISSUE TITLE
readstat_variable_get_val_label or similar extractor?

### ISSUE THREAD

**Issue by dmbates** [WizardMac/ReadStat#117]
Would it be possible to add an extractor function with a signature like
```C
const char* readstat_variable_get_val_label(const readstat_variable_t *variable)
```
to return a pointer to the `name` field of the `readstat_label_set_t` pointed to by the `label_set` field in `*variable`?

I expect you would need to check if the `label_set` field is NULL and return NULL, otherwise return
`label_set + sizeof(readstat_type_t)`.  Alternatively if you reverse the first two fields of the `readstat_label_set_s` struct then you would just need to return the value of the `label_set` field.

The reason for this request is to be able to associate value labels with a variable in the Julia [`ReadStat` package](https://github.com/davidanthoff/ReadStat.jl) using the callback interface without the need to add any glue code in C or C++.

I can create a pull request if you wish but I suspect it is easier to just go ahead and write it if you think this is a good idea.

**Comment by evanmiller** [comment]
Hi, the label set name string that you're looking for is already passed as the 3rd argument to the `readstat_variable_handler`. Looking at the ReadStat.jl code, it looks like the Julia handler is confused and thinks the 3rd argument is the variable label, which (if you need it) should instead by accessed with `readstat_variable_get_label`.

**Comment by dmbates** [comment]
Thanks for the clarification, @evanmiller
