### ISSUE TITLE
Build error for 32 bit targets

### ISSUE THREAD

**Issue by davidanthoff** [WizardMac/ReadStat#119]
I think [this line](https://github.com/WizardMac/ReadStat/blob/66fc2f6ac5238005c190f05d1d3d1a008bb989b1/src/sas/readstat_sas.c#L95) is causing the trouble: when I try to compile things for a 32 bit target, I get an error:

``error: overflow in implicit constant donversion [-Werror=overflow]``

**Comment by evanmiller** [comment]
Thanks. What platform? Can we add it to Travis/Appveyor?

**Comment by davidanthoff** [comment]
I believe Windows 32 bit (i686), Linux 32 bit (i686) and some ARM platform (armv7l).

We have this new binary build infrastructure in julia that does complete cross-compiles on travis for a large number of platforms. The repo for ReadStat is https://github.com/davidanthoff/ReadStatBuilder, and that is where I noticed this. Not sure how easy it would be to add a test on travis/appveyor...

**Comment by evanmiller** [comment]
Ok. Well, I think I've fixed the overflow issue you reported, but there could be other issues impeding the build (as well as additional undefined behavior in the fuzz tests). Apparently Travis has no plans to support 32-bit environments, maybe there's a solution in Appveyor though.

Please open a new issue for additional build errors, and include a complete error log.

**Comment by davidanthoff** [comment]
That did the trick, it seems to compile correctly now. The cross compiling for Julia is happening at https://github.com/davidanthoff/ReadStatBuilder now. Essential that repo pulls the source from your repo and then cross compiles everything on Travis for all sorts of platforms, and then uploads the compiled binaries to the release page. I still need to iron out a few things, but mostly it seems to work. While the main use-case for this is ReadStat.jl, those binaries might be useful for others as well?
