### ISSUE TITLE
Do most file formats need to know the row count when readstat_begin_writing_* is called?

### ISSUE THREAD

**Issue by davidanthoff** [WizardMac/ReadStat#120]
I'm starting to look into providing write support for julia. I am looking broadly at scenarios where the data I want to write comes from an iterator, and in some cases I might not no the length (i.e. number of rows) of the source until I actually iterate the source. Doing so can be costly, and ideally I'd like to stream the data into the file without first iterating it once, just to find out how many rows there are.

I see that ``readstat_begin_writing_sas7bcat`` doesn't need a row count, but all other file formats seem to need the number of rows at that point. Is there a way that in general one doesn't have to specify the number of rows one will write up front?

**Comment by evanmiller** [comment]
Most file formats include the row count at the beginning of the file.

**Comment by davidanthoff** [comment]
Does it always use a fixed number of bits for the row count in the files? I.e. could there be a strategy to write some incorrect row number initially, and then update once all rows have been written?

**Comment by evanmiller** [comment]
Possibly, but the API is designed as an emitter of bytes, without backtracking.
