### ISSUE TITLE
Visual C++ compatibility

### ISSUE THREAD

**Issue by jonathon-love** [WizardMac/ReadStat#131]
hi,

we're about to start using readstat in [jamovi](https://www.jamovi.org), but we use a lot of python 3.5, so needed it to be compatible with VS2015. i've made a bunch of changes so it will build in VS2015, and was wondering if you'd like to accept some of this stuff upstream.

i've taken a very "hack and slash" approach so far, but i can spend some time putting nice #ifdefs in place, etc.

sound good?

with thanks

**Comment by evanmiller** [comment]
Hi, I am happy to accept VS2015 changes provided there is test coverage and continuous integration for the VS2015 features. (I would like to avoid a situation where VS2015 support silently breaks in the future.)

**Comment by jonathon-love** [comment]
oh yeah. that's probably more work than i can give.

cheers, and thanks for readstat.

**Comment by jonathon-love** [comment]
hi,

i've been looking into this again, and seeing if i can add appveyor support for MSVC, but autotools doesn't seem to play nicely with MSVC.

what would be your preferred build strategy here?

with thanks

**Comment by jonathon-love** [comment]
FYI, i maintain a MSVC compatible fork [here](https://github.com/jonathon-love/ReadStat), and a python module [here](https://github.com/jamovi/jamovi-readstat).

**Comment by evanmiller** [comment]
I don't see anything actionable here, so I'm closing the issue. Feel free to re-open if you find a way to have your changes tested with a CI service.

**Comment by ofajardo** [comment]
I support Jonathon's point of view. It would certainly be a big advantage to be able to compile ReadStat with MVSC, for using ReadStat with python (only compiling with mvsc is officially supported). Right now I am still able to compile with mingw, but had to force things and I am not sure how stable that is in the long run.

**Comment by evanmiller** [comment]
What other testing / building strategies did you have in mind? I am open to ideas here. I am somewhat familiar with CMake.

**Comment by jonathon-love** [comment]
yup, transitioning to CMake is something we could pursue.

would you be a:

a) "i'll get started!"
b) "be great if you could start on that, happy to help you out"
c) "don't talk to me until it's done"

jonathon

**Comment by evanmiller** [comment]
Okay, feel free to open a WIP PR. I can help out in the sense of answering questions and integrating, but changing the build system isn't something I can devote a significant amount of time to.
