### ISSUE TITLE
incorrect logic for rle compression

### ISSUE THREAD

**Issue by ankravch** [WizardMac/ReadStat#134]
It appears that readstat_sas_rle.c has incorrect logic for rle compression
```python
ssize_t sas_rle_compress(void *output_buf, size_t output_len,
        const void *input_buf, size_t input_len)
```

Here is a reproducible example by using a public rle compressed sas7bdat file (pgtype 16384)
[obs_all_perf_1.zip](https://github.com/WizardMac/ReadStat/files/1924604/obs_all_perf_1.zip)
It has 65 columns of DOUBLE type, so an uncompressed record length should be 520 bytes.

1) The first compressed record has 404 bytes length:
```python
 for(i=0; i<404; i++){
    #1024=file header, 24=page header, 92=subheader pointers, 156=free bytes
    printf("%02X,", cbuf1[1024+24+92*12+156 +i]);
  }
```
F4,81,3B,40,F3,82,EE,D1,40,F2,83,40,45,D2,40,F3,82,D0,75,40,F3,82,60,76,40,F4,81,22,40,F3,8A,C0,51,40,2F,F5,64,FC,76,A9,13,40,C2,66,8A,A1,9B,40,67,1B,DE,C4,05,E8,38,40,F4,81,10,40,F4,81,22,40,F4,81,10,40,F4,81,1C,40,F4,81,14,40,F4,81,14,40,F4,81,18,40,F4,81,1C,40,F4,81,14,40,F4,81,18,40,F4,81,1C,40,F4,92,18,40,5C,8F,C2,F5,28,8C,46,40,CE,AB,89,67,45,23,34,40,CD,C1,CC,80,4C,D0,BF,79,B2,5A,DE,18,41,34,40,3A,B4,C8,76,BE,DF,43,40,36,5E,BA,49,0C,82,2D,40,B2,E4,17,4B,7E,D1,39,40,54,69,C8,B9,CF,AE,35,40,7D,3F,35,5E,BA,C9,32,40,E2,7A,14,AE,47,C1,36,40,20,36,95,86,9C,7B,3A,40,C2,FF,93,3F,37,40,5C,8F,C2,F5,28,8C,66,40,48,E1,7A,14,AE,A7,66,40,CD,C1,CC,00,03,4C,60,40,29,5C,8F,C2,F5,B8,61,40,48,E1,7A,14,AE,D7,68,40,E1,7A,14,AE,47,71,52,40,85,EB,51,B8,1E,5D,63,40,29,5C,8F,C2,F5,F8,62,40,5C,8F,C2,F5,28,7C,57,40,29,5C,8F,C2,F5,10,61,40,5D,8F,C2,F5,28,2C,67,40,F3,82,70,61,40,F4,81,2E,40,F4,81,30,40,F4,81,2E,40,F4,87,39,40,6E,59,AB,63,82,07,D0,F3,9B,BC,38,40,68,91,ED,7C,3F,75,32,40,F2,D2,4D,62,10,98,38,40,AE,47,E1,7A,14,0E,7E,40,01,F2,8A,BC,78,40,51,B8,1E,85,EB,4D,71,40,C2,CC,82,36,83,40,F2,83,C0,47,D2,40,F3,82,5B,D2,40,F5,80,40,F4,99,32,40,C7,71,1C,C7,71,1C,11,40,EB,51,B8,1E,85,8B,82,40,26,9E,15,8D,04,7C,40,40

2) When I decompress it, I do get a record length=520 bytes.
``` python
  int reclen=404;
  char *data_buf = malloc(reclen*sizeof(char));
  memcpy(&data_buf[0], &cbuf1[1024+24+92*12+156], reclen); 
  char *output_buf = malloc(520*sizeof(char));
  size_t bytes_decompressed = sas_rle_decompress(output_buf,520, data_buf,reclen);
```

3) Here is an issue. When I compress again "output_buf" (from step2), I get a rle record length=403 bytes, but the original rle record length=404 bytes (from step1).
``` python
  size_t compressed_len = sas_rle_compressed_len(output_buf, 520);
  char *rle_data = malloc(compressed_len*sizeof(char));
  size_t actual_len = sas_rle_compress(rle_data, compressed_len, output_buf, 520);
```
F4,81,3B,40,F3,82,EE,D1,40,F2,83,40,45,D2,40,F3,82,D0,75,40,F3,82,60,76,40,F4,81,22,40,F3,8A,C0,51,40,2F,F5,64,FC,76,A9,13,40,C2,66,8A,A1,9B,40,67,1B,DE,C4,05,E8,38,40,F4,81,10,40,F4,81,22,40,F4,81,10,40,F4,81,1C,40,F4,81,14,40,F4,81,14,40,F4,81,18,40,F4,81,1C,40,F4,81,14,40,F4,81,18,40,F4,81,1C,40,F4,92,18,40,5C,8F,C2,F5,28,8C,46,40,CE,AB,89,67,45,23,34,40,CD,C1,CC,80,4C,D0,BF,79,B2,5A,DE,18,41,34,40,3A,B4,C8,76,BE,DF,43,40,36,5E,BA,49,0C,82,2D,40,B2,E4,17,4B,7E,D1,39,40,54,69,C8,B9,CF,AE,35,40,7D,3F,35,5E,BA,C9,32,40,E2,7A,14,AE,47,C1,36,40,20,36,95,86,9C,7B,3A,40,C2,FF,93,3F,37,40,5C,8F,C2,F5,28,8C,66,40,48,E1,7A,14,AE,A7,66,40,CD,C1,CC,00,03,4C,60,40,29,5C,8F,C2,F5,B8,61,40,48,E1,7A,14,AE,D7,68,40,E1,7A,14,AE,47,71,52,40,85,EB,51,B8,1E,5D,63,40,29,5C,8F,C2,F5,F8,62,40,5C,8F,C2,F5,28,7C,57,40,29,5C,8F,C2,F5,10,61,40,5D,8F,C2,F5,28,2C,67,40,F3,82,70,61,40,F4,81,2E,40,F4,81,30,40,F4,81,2E,40,F4,87,39,40,6E,59,AB,63,82,07,D0,F3,9B,BC,38,40,68,91,ED,7C,3F,75,32,40,F2,D2,4D,62,10,98,38,40,AE,47,E1,7A,14,0E,7E,40,01,F2,8A,BC,78,40,51,B8,1E,85,EB,4D,71,40,C2,CC,82,36,83,40,F2,83,C0,47,D2,40,F3,82,5B,D2,40,F5,80,40,F4,97,32,40,C7,71,1C,C7,71,1C,11,40,EB,51,B8,1E,85,8B,82,40,26,9E,15,8D,04,7C,D0

4) The difference between the original rle compressed record (from step 1) and the one created by "sas_rle_compress" (from step2) is only in few bytes:
```python
>>> [(i,j) for i, j in zip(a[:-1], b) if i != j]
[('99', '97'), ('40', 'D0')]
```
I guess it's a minor bug that should easy to fix (for one who wrote the code). I have to take a look at the code myself too.

**Comment by ankravch** [comment]
Actually it's not a problem that sas_rle_compress compresses 520 bytes into 403 (instead of 404 bytes).

I just had to replace subheader offset, length of subheader and free bytes properly. 
And then the modified sas7bdat file can be viewed by SASViewer.

```python
  char new_fb[4] = {0x9D, 0x00, 0x00, 0x00}; //157=00 00 00 9D free bytes (original value=156)
  memcpy(cbuf1+1024+12, new_fb, 4);

  char new_sho[4] = {0x05, 0x05, 0x00, 0x00}; //1285=00 00 05 05 offset from page start to subheader (original value=1284)
  memcpy(cbuf1+1024+24+90*12, new_sho, 4);

  char new_shl[4] = {0x93, 0x01, 0x00, 0x00}; //403=00 00 01 93 length of subheader (original value=404)
  memcpy(cbuf1+1024+24+90*12+4, new_shl, 4);
```
Now I can append new data pages (pgtype16384) to already existing rle compressed sas file. So that a resulting sas7bdat can be viewed by SASViewer.

**Comment by evanmiller** [comment]
Hi, I'm somewhat confused by your post here - is there a bug here or not? Compression isn't necessarily unique... a bug would be if SAS and ReadStat decompress the same compressed bytes to different decoded bytes.

I'm not quite sure what to make of your second post, is that a separate bug?

**Comment by evanmiller** [comment]
Without a more specific bug report there is nothing I can do here. Closing issue. Please open a new issue if you can provide a *minimal* test case that proves a bug exists.
