### ISSUE TITLE
Cannot successfully convert from CSV to SAV

### ISSUE THREAD

**Issue by thelgis** [WizardMac/ReadStat#135]
Hello readstat team,

I am trying to convert a small csv file (Test.csv) using a metadata JSON (schema.json). 

Running the command: 
`readstat -f Test.csv schema.json output.sav`

produces a success message: 
`Converted 2 variables and 6 rows in 0.00 seconds`

Nevertheless, when the SAV file is opened by SPSS only the columns are there but the actual row data is missing. 

My apologies if this is not a bug and I am missing something obvious but reading the documentation I am under the impression that this should be working. 

All files to reproduce are attached: 
[Test.csv.gz](https://github.com/WizardMac/ReadStat/files/1955458/Test.csv.gz)
[schema.json.gz](https://github.com/WizardMac/ReadStat/files/1955460/schema.json.gz)
[output.sav.gz](https://github.com/WizardMac/ReadStat/files/1955456/output.sav.gz)

Thank you for your time

**Comment by thelgis** [comment]
In case it helps: 

the example above works properly by checking out commit 2d81fa2dd59d2d970abf55c3e952510ed93a990c

**Comment by HelloFy** [comment]
what time this bug  can be solved？

**Comment by evanmiller** [comment]
Should be fixed now. Thanks for the report.
