### ISSUE TITLE
Use of stderr

### ISSUE THREAD

**Issue by hadley** [WizardMac/ReadStat#14]
R CMD check complains:

```
* checking compiled code ... NOTE
File ‘haven/libs/haven.so’:
  Found ‘___stderrp’, possibly from ‘stderr’ (C)
    Objects: ‘readstat_por.o’, ‘readstat_por_parse.o’,
      ‘readstat_sas.o’, ‘readstat_sav.o’, ‘readstat_sav_parse.o’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor the C RNG.
```

this isn't a huge problem, but it would be nice if there was some alternative way to capture error messages, rather than sending them to stderr.

**Comment by evanmiller** [comment]
Maybe we can add an error/warning handler callback?

**Comment by hadley** [comment]
That seems like a reasonable approach to me

**Comment by evanmiller** [comment]
There's now an error handler API in the new design:

https://github.com/WizardMac/ReadStat/blob/master/src/readstat.h#L83

By default nothing happens. It would be nice to print to stderr by default in a way that doesn't trigger the R CMD warning.
