### ISSUE TITLE
[SAS7BDAT] Question about a bitmask

### ISSUE THREAD

**Issue by amweiss** [WizardMac/ReadStat#142]
There's a bitmask for sas7bdat files defined here:
https://github.com/WizardMac/ReadStat/blob/68d7a59a503466f23501bf85a7c515626a1af0ff/src/sas/readstat_sas.h#L94

Can anyone explain where it came from? We are currently seeing a page type value of 384, which doesn't match the Shotwell "SAS7BDAT Database Binary Format" paper, but does seem to be handled correctly as a data page in ReadStat since the mask brings it down to 256. So no problem with ReadStat here, just wondering if this is a slight change in the file format or something that has been seen before that the mask handles.

Thanks.

**Comment by evanmiller** [comment]
Hi,

I don't have an answer, I think that just came from general reverse engineering. You may also wish to refer to the Python sas7bdat package, which is an independent implementation.
