### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by davidanthoff** [WizardMac/ReadStat#144]
@evanmiller would be great if you could tag a new release with a version number. The last one is two years old, and it would be easier on my end if I could reference a specific version I'm wrapping on the julia side.

**Comment by davidanthoff** [comment]
Bump, any chance you could tag a release?

**Comment by evanmiller** [comment]
Hi, sorry about the release neglect. I'll get one out the door soon, currently waiting on OSS-Fuzz integration to be complete.

**Comment by evanmiller** [comment]
I (finally) have a tagged release / pre-release `v1.0.0-rc0` here:

https://github.com/WizardMac/ReadStat/releases

I'll do a few more release candidates in the coming weeks and then a final 1.0 release if everything looks good. Closing issue.
