### ISSUE TITLE
pyreadstat: new python wrapper. Please advice on license

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/ReadStat#147]
Dear @evanmiller, authors and collaborators:

I am pleased to announce I have released (open source under Apache 2.0 license) a new python package "pyreadstat" that wraps ReadStat. It has been tested with Python 3 (3.5, 3.6, 3.7) for linux and windows. Only reading supported at the moment.

The repo can be found here:  https://github.com/Roche/pyreadstat.

Besides giving credit to Readstat in the Readme, I have copied the Readstat License into the License file of pyreadstat, as I have understood that is the way to proceed. Please advice if there is anything else to do in order to give proper credit to your great work and be compliant with the licensing.

And if you like the project, it would be great to be listed in the language bindings section of the Readstat readme.

Thanks in advance.

**Comment by evanmiller** [comment]
That's fine, I went ahead and added your binding to the list. Thanks!

**Comment by ofajardo** [comment]
@evanmiller just heads up in case you were not aware: pyreadstat was added as a backend to python's pandas.read_spss, meaning now everyone reading spss files with pandas is using Readstat via pyreadstat. That was added around July 2019 already. I Just thought it would be nice for you to know, in case you didn't.

Maybe pandas adds SAS and Stata at some point (they have their own older functions, but adding pyreadstat would solve some issues they have with their old code)

**Comment by evanmiller** [comment]
@ofajardo Very cool! Thanks for letting me know.
