### ISSUE TITLE
Revamp API to use setHandler pattern

### ISSUE THREAD

**Issue by evanmiller** [WizardMac/ReadStat#15]
Currently each callback must be passed as a separate argument to the parse_* functions. This limits future flexibility for adding other handlers, e.g. an error handler as discussed in #14. A better API would look something like

    readstat_parser_t parser = readstat_parser_init();
    readstat_set_info_handler(parser, &my_info_handler);
    readstat_set_variable_handler(parser, &my_variable_handler);
    readstat_error_t status = readstat_parse(parser, "/path/to/file");
    readstat_parser_free(parser);

**Comment by evanmiller** [comment]
A first stab at a new API is in this branch:

https://github.com/WizardMac/ReadStat/tree/new-api

The new `readstat.h`:

https://github.com/WizardMac/ReadStat/blob/new-api/src/readstat.h

Usage notes:

https://github.com/WizardMac/ReadStat/commit/f6809c036745357ce7b2ff6c2b23fa4d5ee31f46

**Comment by hadley** [comment]
I like it. It'll actually make my life simpler, and I was going to ask that you add the `readstat` prefix to the parser functions any way :)

**Comment by evanmiller** [comment]
While I'm breaking things, I think I'll shorten these `*_callback` names to `readstat_info_handler` etc.

**Comment by hadley** [comment]
I'd also suggest adding a few comments that describe the overall design of the API.

**Comment by evanmiller** [comment]
I've merged in the `new-api` branch, closing. Still have an open issue for "More documentation" so I'll address the overall API design there.
