### ISSUE TITLE
New time display format for SPSS

### ISSUE THREAD

**Issue by khc8749** [WizardMac/ReadStat#155]
I believe there needs to be a new Readstat SPSS time format added.

SPSS
--------------------------------------
Duplicate display format

SPSS format                = mm:ss
Readstat format            = TIME5

SPSS format                = hh:mm
Readstat format            = TIME5

**Comment by evanmiller** [comment]
Hi, I need more information to do anything about this. Were new time formats introduced in SPSS 25?

**Comment by khc8749** [comment]
Here you go.  Let me know if you need anything else

[spss25_hh_mm.zip](https://github.com/WizardMac/ReadStat/files/2687303/spss25_hh_mm.zip)
