### ISSUE TITLE
Error - unsupported features - most recent version of SPSS (v25) portable file

### ISSUE THREAD

**Issue by zross** [WizardMac/ReadStat#157]
I reported an issue in the haven [GitHub page](https://github.com/tidyverse/haven/issues/412) but I'm seeing that it may be a ReadStat issues. I'm finding that haven/ReadStat is working fine with earlier versions of SPSS but is reporting an error when reading in a `.por` file created by SPSS v25 -- even a super-simple file. When running directly in ReadStat I also see an issue.

In the attached zip I included both a `.sav` and a `.por` of the exact same data created from the most recent version of SPSS and I find that reading the `.sav` works perfectly while the `.por` reports an error.

```sh
# Works perfectly
readstat -f tiny_spss25_locale.sav sav.csv
```

```sh
# Error
readstat -f tiny_spss25_locale.por por.csv
# Error processing tiny_spss25_locale.por: Invalid file, or file has unsupported features
```

Any suggestions?

[tiny_spss25_locale.zip](https://github.com/WizardMac/ReadStat/files/2600589/tiny_spss25_locale.zip)

**Comment by evanmiller** [comment]
Fixed in https://github.com/WizardMac/ReadStat/commit/3b613a10b6bd2945b0b9b4c834a4d0cef24e7261

**Comment by zross** [comment]
Wow, impressively fast! Thank you.
