### ISSUE TITLE
SPSS 25 POR files date formats NULL

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/ReadStat#160]
This is coming from #158.  

Not so important, but I file the observation anyway:

the example por file in the previous issue contains 3 columns with date, datetime and time formats. Somehow SPSS is able to read them correctly (with formatted dates). ReadStat readstat_variable_get_format however returns NULL, and therefore there is no information to reformat those variables. 
Otherwise the file is read correctly and for those 3 columns correct timestamps are returned.

**Comment by evanmiller** [comment]
Hi, it appears that SPSS has introduced new date formats. Each format corresponds to an integer - if you can find a reference for these new formats, I can add support.

**Comment by ofajardo** [comment]
I'll try to find the info, I guess it won't be easy.

Would it be possible to return those integers (as is or as a string)? Normally I take those internal codes and decide how to convert the numeric timestamp to a python object. 
I am not really interested on getting the datetimes as a string (if that is what you meant by adding support), but what I can do if I get those integers is to generate a por file with all possible formats and then come back to you with a translation table from int to string. I can do for sav as well if it helps.

**Comment by evanmiller** [comment]
Hi,

We have most of the codes here:

https://github.com/WizardMac/ReadStat/blob/master/src/spss/readstat_spss.h#L2-L38
https://github.com/WizardMac/ReadStat/blob/master/src/spss/readstat_spss_parse.rl#L38-L75

I just need to know the new codes so I can update appropriately.

**Comment by evanmiller** [comment]
Not sure why but the date/time format codes in the linked POR file seem to be shifted up by 82. I've implemented a workaround here:

https://github.com/WizardMac/ReadStat/commit/8aec75529193bc125fc66f68f23d97be5b61cae6
