### ISSUE TITLE
sas7bdat user defined missing values 64 bit

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/ReadStat#161]
This is coming from #159:

when a sas7bdat file produced on 64 bit linux is read, readstat_value_is_tagged_missing returns False for those missing values. It should return True and then readstat_value_tag should return a valid char, from A to Z and _

Attached a sample file with 9 columns and 1 single row.

cols 1 to 6: A, B, C, X, Y, Z
col 7: _ (underscore)
col 8: . (system missing, here readstat_value_is_system_missing should return true)
col 9: 1 (not missing, just a double value).
[missing_test.zip](https://github.com/WizardMac/ReadStat/files/2691045/missing_test.zip)

**Comment by evanmiller** [comment]
Thanks for the sample file.

Some notes for myself:

It looks like these files encode the tag as:

```
A - 2 + ~((value >> 40) & 0xFF)
```

E.g. `0xFD` = A, `0xFC` = B, `0xFB` = C, `0xE4` = Z

Older versions encode the tag as

```
~((value >> 40) & 0xFF)
```

These schemes would be compatible, except for the tagged underscore case. This is encoded as `0xFF` in the new files, but the old files used `0xFF` as the system-missing value. The new files used `0xFE` as system-missing.

Ideally, we would figure out what triggers the new scheme. Is it a difference between 64-bit and 32-bit versions of SAS? Is there a separate flag within the file somewhere? Does it only apply when width = 3?
