### ISSUE TITLE
The following sas7bdat from census failed to be parsed

### ISSUE THREAD

**Issue by huapeng01016** [WizardMac/ReadStat#162]
We get a parse error using the latest ReadStat to convert the following sas7bdat file. 

[AHS 2013 National Public Use File PUF Flat File](http://www2.census.gov/programs-surveys/ahs/2013/AHS%202013%20National%20PUF%20v1.2%20Flat%20SAS.zip?#)

**Comment by evanmiller** [comment]
Duplicate of #21

**Comment by ofajardo** [comment]
That error code would indeed be very helpful.

**Comment by evanmiller** [comment]
The error code I receive with this file is `READSTAT_ERROR_UNSUPPORTED_COMPRESSION`. Do you see something different?

**Comment by evanmiller** [comment]
Please try the new code branch:

https://github.com/WizardMac/ReadStat/tree/sas-binary-compression
