### ISSUE TITLE
Are there interests for a Visual C++ 2017 project? 

### ISSUE THREAD

**Issue by huapeng01016** [WizardMac/ReadStat#163]
I have a private fork of ReadStat to compile with Visual C++ 2017 and the ability of using ICU instead of iconv for the Unicode conversion. If people are interested,  I could try to submit it for the author to consider to include it in the official repo.

**Comment by ofajardo** [comment]
I am interested. I maintain a python package binding Readstat and to be able to compile with Visual Studio 2015 would be very useful. 
There is a similar discussion here https://github.com/WizardMac/ReadStat/issues/131. In summary the first step would be to change the building of readstat from autotools to cmake.

**Comment by evanmiller** [comment]
CC @jonathon-love

**Comment by jonathon-love** [comment]
hi @huapeng01016,

i maintain a fork with VC support over [here](https://github.com/jonathon-love/ReadStat), relevant [diff is here](https://github.com/jonathon-love/ReadStat/commit/7f13782b7c11f1087d8b990603195cf62a17a62a)

feel free to use that as a starting point (or not). as you'll see, the combination of mallocs and gotos makes it a little inelegant, but i was trying to minimise the number of changes for review.

jonathon

**Comment by evanmiller** [comment]
Since there is nothing actionable here, I am closing the issue. Feel free to open a pull request with WIP code to continue the discussion.
