### ISSUE TITLE
user defined missing value not interpreted correctly in sas7bcat files

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/ReadStat#164]
This is a bit a corner case, but I report it for completeness now that I found it:

In sas7bdat file we can have user defined missing values (A to Z and _ ). Readstat is already reading them correctly.

In sas7bcat we can define a label for those values, but I think those are not interpreted correctly by Readstat.

In the attached sas7bdat files I have missing values A, B, C, X, Y, Z, _ and a system missing . and then the value 1 in a single row, each in one column.

In the sas7bcat file I define a val_label "A" and a label "missing" which I assign to the user defined missing value A.

(these definitions can be seen in the also attached .sas file)

Now, when using handle_value_label

Readstat reads correctly the val_label and the label, but for the value in this case (which should be A), I was expecting that readstat_value_is_tagged_missing evaluated to 1, so that I can recover the tag A with readstat_value_tag. However that is not the case, readstat_value_is_tagged_missing evaluates to 0 while readstat_value_is_system_missing actually evaluates to 1 (when it should not). So, at the end I can recover only a NaN, but that it is not distinguishable from a true system_missing and therefore not very useful.

I hope to have explained myself well enough. Thanks.

[missing_data.zip](https://github.com/WizardMac/ReadStat/files/2773736/missing_data.zip)

**Comment by evanmiller** [comment]
Please try the latest commit. The new SAS7BDAT tag logic was not being used in the BCAT reader. Now they should both use the same logic.

**Comment by ofajardo** [comment]
It works! Thanks.

Unrelated, but I confirm it works for Stata dta as well.
