### ISSUE TITLE
SAS dataset with no columns throughs generic error

### ISSUE THREAD

**Issue by thays42** [WizardMac/ReadStat#165]
Hello,

I'm attempting to address a [PR](https://github.com/tidyverse/haven/issues/420) for the R package Haven. It appears that when readstats is presented with a SAS dataset with no columns, it throws an "Unable to allocate memory" error. 

Steps to reproduce:
1. Acquire a SAS dataset with 0 columns:
```
libname out '~';

data out.some_data;
run;
```

2. Run the following:
```$ readstat some_data.sas7bdat some_data.csv
ReadStat: Error parsing page 0, bytes 65536-131071
Converted 0 variables and 0 rows in 0.00 seconds
Error processing some_data.sas7bdat: Unable to allocate memory
```

This error message seems somewhat misleading. Would it be possible to provide a more specific error message related to the dataset having no columns? 

Thanks!

**Comment by evanmiller** [comment]
Thanks. Fixed in dev.
