### ISSUE TITLE
warning: macro 'AM_ICONV' not found in library

### ISSUE THREAD

**Issue by kylebarron** [WizardMac/ReadStat#171]
I was just trying to build this again, and I can't build from master anymore. I googled and found that this error is usually due to an out of date or missing `gettext`, though I have gettext 0.19.8.1 installed.

Running `./autogen.sh` gives:
```
configure.ac:40: warning: macro 'AM_ICONV' not found in library
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: You should add the contents of the following files to 'aclocal.m4':
libtoolize:   '/homes/nber/barronk-dua51929/local/anaconda3/share/aclocal/libtool.m4'
libtoolize:   '/homes/nber/barronk-dua51929/local/anaconda3/share/aclocal/ltoptions.m4'
libtoolize:   '/homes/nber/barronk-dua51929/local/anaconda3/share/aclocal/ltversion.m4'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:40: warning: macro 'AM_ICONV' not found in library
configure.ac:40: error: possibly undefined macro: AM_ICONV
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

Compiling from 08c364729507a7ea8317941f3330330c30daef07 works fine, so I'll just do that for now.

**Comment by evanmiller** [comment]
What operating system / version are you on? `gettext` is now required for bootstrapping from autotools, but it will not be required in the packaged releases. (Hope to move to a frequent packaged release system soon.)

**Comment by kylebarron** [comment]
I can check on Monday, but I just know it's Scientific Linux 7, which is a fork of CentOS 7. I was eventually able to get it to work by compiling on my personal Linux box and moving it to the remote Linux machine, since it appears it's a static executable.

**Comment by evanmiller** [comment]
Thanks for the information. Yes, gettext is only needed for the very first step, `./autogen.sh`. You can copy the files after that step so that configuration and compilation takes place on the host machine.

**Comment by evanmiller** [comment]
I have a release / pre-release out now (1.0.0-rc0 - https://github.com/WizardMac/ReadStat/releases), so this will no longer be an issue for casual downloaders. Closing issue.

**Comment by kylebarron** [comment]
That's great! Thanks so much!
