### ISSUE TITLE
readstat not converting encoding of XPORT variable labels

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/ReadStat#172]
This is comming from [this issue](https://github.com/Roche/pyreadstat/issues/18) in pyreadstat.

This file contains variable labels with non-ascii characters, the first one appearing in column index 173:

```
o,p\x92-DDT comment code
```

\x92 seems to be a windows-1252 for apostrophe if I translate manually to utf-8, so theoretically iconv should translate it correctly, however it does not. I try to set the encoding with readstat_set_file_character_encoding and still it seems that readstat ignores it. 

I have observed that most readstat_parse_* functions (sas7bdat, sas7bcat, dta, sav) have lines 

```
ctx->input_encoding = parser->input_encoding;
 ctx->output_encoding = parser->output_encoding;
```
But I don't see them in xport, also not in por. Maybe the conversion is not enabled?

sample file is [here](https://github.com/Roche/pyreadstat/files/2848634/2001-2002.L28POC_B.XPT.gz)

**Comment by ofajardo** [comment]
Solved! I read your comment regarding xport files produced by recent sas stamping the encoding on the file. I guess you already have samples, but if not let me know, I can produce some in SAS 9.3 (but on unix, meaning probably the encoding will be UTF-8)

**Comment by evanmiller** [comment]
I don't have any samples actually. If you could point me to a file that contains the encoding stamp, I'll see about adding support.

**Comment by ofajardo** [comment]
[Here](https://github.com/Roche/pyreadstat/blob/master/test_data/basic/sample.xpt) is a file I produced on SAS 9.4 on Linux (should be using UTF-8 as encoding).

But maybe I misunderstood you regarding the encoding stamp ... I thought you said that old version did not produce the stamp while recent versions do produce the stamp. If that is true my file should have the stamp. However I don't know how to check that, so I cannot confirm if this file does have the stamp or not.

**Comment by evanmiller** [comment]
Thanks. That file appears to be in the XPT Version 5 format (not the 8+ format). I do not see anything obvious in the file indicating an encoding indicator.

**Comment by ofajardo** [comment]
OK got it. I'll check if I can produce a file in the 8+ format.

**Comment by ofajardo** [comment]
OK I think I managed to produce xport files in version 9, see attached zip. The file normal can be opened by Readstat, contains just one column and one numeric value. The other file cannot be opened. The thing is that it has long labels and it seems Readstat cannot digest those. 
I created the files following this example, there you can see what I mean by long labels, to create the normal one I just used a short label.

https://documentation.sas.com/?docsetId=movefile&docsetTarget=p13q0v60f08mj3n1ebm8salcpkmh.htm&docsetVersion=9.4&locale=en#p0mfj6mmx84kzpn1vxgdafc02xd3

[transport_v9.zip](https://github.com/WizardMac/ReadStat/files/2884068/transport_v9.zip)
