### ISSUE TITLE
ICONV_CONST Not defined

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/ReadStat#173]
Just a question:

For compiling pyreadstat I am following the same way as Haven does: I copy the content of the Readstat src folder into pyreadstat and I compile there using the cannonical python tools. That means I am not using autotools. I would like to keep this way in the future because it is very simple.

Today I grabbed the latest source code and I got an error when trying to compile this line in readstat_iconv.h as it seems that ICONV_CONST is not defined anywhere:

```
typedef ICONV_CONST char ** readstat_iconv_inbuf_t; 
```

Reading other issues I understand that this is somehow going to become defined when doing autogen.sh. Indeed for me compiliing Readstat with autotools works perfectly well. 

For now, just to see what happens I defined that macro manually:

```
#define ICONV_CONST const
```
and that makes pyreadstat being happy again. If I define the macro to be empty, it also compiles fine and tests pass.

How could I improve this? Any suggestions for my process? Is it something that is going to be solved by itself once you do a release?

thanks

**Comment by evanmiller** [comment]
Thanks for bringing this issue to my attention. I'll add some fallback logic so that copy-pasting the source code continues to work as before (though it may trigger some compile-time warnings).

**Comment by ofajardo** [comment]
works! thanks!
