### ISSUE TITLE
Feature request: csv input from stdin

### ISSUE THREAD

**Issue by kylebarron** [WizardMac/ReadStat#174]
Thanks for all your hard work!

In case it's not too much work, I wanted to see if it's possible to allow CSV input to be read from stdin. My use case is that I'm trying to go from Spark to Stata/SAS files. There's no way to export directly from Spark to Stata or SAS files, so I'm exporting to CSV and then using Readstat to convert from csv. But the parallel nature of Spark means that it's [compute intensive](https://stackoverflow.com/questions/31674530/write-single-csv-file-using-spark-csv) to save as a single CSV file, and instead saves as a _directory_ with ~200 individual csv parts of the full file. It's not possible to convert multiple CSV files to DTA with ReadStat, so I was hoping to run `cat *.csv | readstat  metadata.json output.dta`

**Comment by evanmiller** [comment]
It's a reasonable request, but the code isn't really set up for streaming input from stdin. The problem is that ReadStat needs to know the row count before writing the file header. Currently ReadStat parses CSV files twice, first to get the row count, second to get the data. AFAIK it's not possible to read from stdin in two passes.

**Comment by kylebarron** [comment]
That's fine. It's straightforward to `cat *.csv > full.csv`.

One last thing: is there a core reason why numeric CSV to DTA only supports floats? My C isn't great, but I've been trying to edit the code to allow `INT16` in the JSON schema, which would convert a numeric value to a Stata `int`. Is this something you would be interested in? I could submit a WIP PR...

**Comment by evanmiller** [comment]
I didn't implement the CSV features; most likely the author of that code didn't need integer columns, and simply didn't get around to supporting them. Feel free to contribute a PR.
