### ISSUE TITLE
SAV character missing not reported as missing

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/ReadStat#176]
In SPSS Sav, in a character variable you can set up to 3 discrete user defined missing values. When readstat encounters one of those, readstat_value_is_missing should give 1, but instead gives 0. readstat_value_is_defined_missing should also give 1 and it gives 0.

In the attached file, there is only one column and two rows. The first row contains a user defined missing value "Z", this one in my opinion should give 1 for readstat_value_is_missing and readstat_value_is_defined_missing. 

readstat_variable_get_missing_ranges_count and company(readstat_variable_get_missing_range_lo and hi) gives however the correct result ('Z' for both hi and lo, which is correct)

Just for reference the second row has a value "a" wich has a label "labelled" which is correctly read by readstat.

I am working with the latest source on dev. 
[sample_char_missing.sav.tar.gz](https://github.com/WizardMac/ReadStat/files/2871825/sample_char_missing.sav.tar.gz)

**Comment by evanmiller** [comment]
Thanks for the report. Please try:

https://github.com/WizardMac/ReadStat/commit/3a7fedcb0af6b97d2308ca061bd23781b6ea3915

**Comment by ofajardo** [comment]
perfect! thanks!
