### ISSUE TITLE
Invalid CSV output when field has double quotes

### ISSUE THREAD

**Issue by imathews** [WizardMac/ReadStat#178]
Readstat is currently producing invalid CSVs when there is a double quote (`"`) within a field (I'm specifically experiencing this when converting from .dta).

I've created a test file that looks like 
```
| var1     | var2         |
---------------------------
| No quote | "quoted"value|
```
A csv representing this content should double each quote within the field:
```
var1,var2
"no quote","""quoted""value"
```
However, the output produced by Readstat looks like:
```
var1,var2
"no quote",""quoted"value"
```

I've attached files below that demonstrate this behavior. Thank you!

[dta_to_csv_quote_example.zip](https://github.com/WizardMac/ReadStat/files/2950252/dta_to_csv_quote_example.zip)

**Comment by evanmiller** [comment]
Thanks for the report - see if this fixes things:

https://github.com/WizardMac/ReadStat/commit/0789769dcd6bb392d9501c74a49a746c00a6bdf9

**Comment by imathews** [comment]
Apologies for the delay — just got the opportunity to test this, and appears to be working great. Many thanks!
