### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by quantbabies** [WizardMac/ReadStat#18]
Can't build on CentOs 6.6 with gcc 4.4.7

**Comment by evanmiller** [comment]
What is the error?

**Comment by quantbabies** [comment]
Got it to build.  Posting my make file in case anyone else runs into trouble.
(Make sure to have ragel, zlib headers, and lzma headers before building)
CC=c99
PREFIX=/usr/local
RAGEL=/usr/local/bin/ragel
DYLIB=obj/libreadstat.so
all:
	@mkdir -p obj
	[ -x $(RAGEL) ] && $(RAGEL) src/readstat_por_parse.rl -G2
	[ -x $(RAGEL) ] && $(RAGEL) src/readstat_sav_parse.rl -G2
	$(CC) -Os src/*.c -rdynamic -shared -fPIC -o $(DYLIB) -llzma -lz -lm -Wall -Wno-multichar -Werror -pedantic -DHAVE_LZMA

install: all
	@mkdir -p $(PREFIX)/lib
	@cp $(DYLIB) $(PREFIX)/lib/
	@mkdir -p $(PREFIX)/include
	@cp src/readstat.h $(PREFIX)/include/

clean:
	rm -rf obj
