### ISSUE TITLE
read SAS7BDAT dataset label

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/ReadStat#180]
A sas7bdat file can contain what they call "Label" (see screenshot). This is currently not retrieved by Readstat. Would it be possible to get it?

In this example the "Data Set Name" with value "TEST_DATA" goes to readstat file_label. readstat table_name in the other hand is NULL. Maybe the sas7bdat "Label" ("mytest label") could go there in table_name? Anywhere else is also fine.

Attached file example and screenshot. 

[test_data_linux.zip](https://github.com/WizardMac/ReadStat/files/3151428/test_data_linux.zip)

![sas_test_data_label](https://user-images.githubusercontent.com/17498727/57283190-e3348080-70ae-11e9-9b5c-890b740886bc.png)

Here another file with the very same characteristics except it was produced on windows, just to confirm the solution would work for both systems:

[test_data_win.zip](https://github.com/WizardMac/ReadStat/files/3151456/test_data_win.zip)

**Comment by evanmiller** [comment]
Thanks. It would help to know if this file feature is documented somewhere (e.g. the Shotwell Vignette)

**Comment by ofajardo** [comment]
unfortunately it does not look like it is documented in the shotwell vignette or anywhere else.

**Comment by evanmiller** [comment]
Fixed in #213, will close when it reaches master.

**Comment by ofajardo** [comment]
testing with readstat 1.1.5 RC0: 

* test_data_linux.sas7bdat: all good! file_label contains now "mytest_label"
* test_data_win.sas7bdat: file_label contains "                DATASTEPmytest label" @reikoch 

In both cases table_name contains "TEST_DATA" which is good

**Comment by evanmiller** [comment]
@ofajardo Thank you for the report. It appears the file label identification code is looking in the correct vicinity, but has uses some fragile logic / heuristics to pull out the label itself.

I suspect there will be a pointer to the file label somewhere else in the file. In the Windows file you provided, it looks like the end of the file has some previously unidentified text blob pointers. Starting at byte 130938, I see

* Offset=8, Length=4
* Offset=36, Length=12 <--- File label??
* Offset=20, Length=8
* Offset=0, Length=0
* Offset=12, Length=8
* Offset=28, Length=8

Reordering these and lining up with the text blobs, I get

```
Blob:          0000                   DATASTEP mytest label
Length:        [ 4 ][   8   ][   8   ][   8   ][     12     ]
Offset:        8    12       20       28        36
```

So I think these are the pointers we need, but I'm not sure how to reliably locate them.

In any event: without other changes, I will plan to ship as-is and we can leave this open until the bugs are worked out.

**Comment by ofajardo** [comment]
Sounds good! Thanks!

**Comment by evanmiller** [comment]
@ofajardo @reikoch Please try this commit with compressed + uncompressed files as well as labeled + unlabeled files 

https://github.com/WizardMac/ReadStat/commit/6b2bcc5a40688cc1d50cfa00168ff5bb6f3dff96

**Comment by ofajardo** [comment]
all my tests with different files including now the two reported here work now, thanks!
Unfortunately I don't have more files with labels produced on windows.

**Comment by evanmiller** [comment]
Okay, excellent to hear! It seems I have found a robust method then. I will leave this open until the final 1.1.5 release in case there are additional bugs with it. But I feel much more confident in the code now.

**Comment by reikoch** [comment]
Found no problems executing 1.1.5-rc1 against all my sas7bdat test files - congratulations!

**Comment by evanmiller** [comment]
@reikoch Thanks for letting me know! FYI I've opened a pull request over on the original SAS7BDAT vignette with my "discovery" (https://github.com/BioStatMatt/sas7bdat/pull/15)

**Comment by evanmiller** [comment]
1.1.5 has been released with feature. Closing issue.
