### ISSUE TITLE
Activate remaining 7 fuzzers in OSSFuzz

### ISSUE THREAD

**Issue by Google-Autofuzz** [WizardMac/ReadStat#181]
Hello readstat team,

currently the oss-fuzz configuration of this project only uses 6/13 fuzzers.
Is there any reason why the remaining 7 fuzzers are not activated?

Google AutoFuzz Team

**Comment by evanmiller** [comment]
What needs to be done? This is not a very helpful notification.

**Comment by Google-Autofuzz** [comment]
Hello readstat team,

sorry for the missing details.
The script
https://github.com/google/oss-fuzz/blob/master/projects/readstat/build.sh
only builds 7 of the mentioned 13 fuzzers.
It would be great if the remaining fuzzers could be activated as well.

Google AutoFuzz Team

**Comment by evanmiller** [comment]
Thanks for the clarification. IIRC the remaining 7 fuzzers did not traverse very many code branches and so did not pass the OSS Fuzz validation phase.

**Comment by Google-Autofuzz** [comment]
Hello readstat team,

could you still add these fuzzers?
If there are problems with getting them committed, we might be able to help.

Google AutoFuzz Team

**Comment by evanmiller** [comment]
Here is the kind of error I get locally:

```
$ sudo python infra/helper.py check_build readstat
Running: docker run --rm -i --privileged -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -v /home/emiller/oss-fuzz/build/out/readstat:/out -t gcr.io/oss-fuzz-base/base-runner test_all
INFO: performing bad build checks for /out/fuzz_format_por.
INFO: performing bad build checks for /out/fuzz_format_sav.
INFO: performing bad build checks for /out/fuzz_compression_sav.
INFO: performing bad build checks for /out/fuzz_format_sas7bdat.
INFO: performing bad build checks for /out/fuzz_format_sas7bcat.
INFO: performing bad build checks for /out/fuzz_format_dta.
INFO: performing bad build checks for /out/fuzz_format_xport.
INFO: performing bad build checks for /out/fuzz_compression_sas_rle.
Broken fuzz targets (1):
fuzz_compression_sas_rle:
BAD BUILD: /out/fuzz_compression_sas_rle seems to have only partial coverage instrumentation.
ERROR: 12% of fuzz targets seem to be broken. See the list above for a detailed information.
Check build failed.
```

What do you suggest?

**Comment by Google-Autofuzz** [comment]
Hello readstat team,

I think the ossfuzz team better understands how problematic these errors are.
Maybe just create a pull-request mentioning the result of the check_build tool.
My understanding is, that it's just an heuristic that, according to the comments, is just barely working for some examples. It does not scale with e.g. binary size or similar.

Google AutoFuzz Team

**Comment by Google-Autofuzz** [comment]
Hello readstat team,

The OSS-Fuzz team told us, that fuzzers that fail the check_build test can be whitelisted here:
https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/test_all#L121
Hope this helps.

Google AutoFuzz Team

**Comment by evanmiller** [comment]
Thanks for the information. Do I need to patch the whitelist in my pull request?

**Comment by Google-Autofuzz** [comment]
Hi,

To give a bit more context, the check for the builds requires a minimum of coverage for fuzzers. Looking at the ones that fail for readstat, they seem to trigger coverage only on specific files (for instance the compression sas rle fuzzer only seems to trigger coverage in the sas/readstat_sas_rle.c file). There are two options on how to approach this, one is to just whitelist the fuzzers in the test_all file that we described above, the other would be to try and get to fuzz files like readstat_sas_rle.c while also fuzzing other parts of readstat.

What would make more sense from your point of view?

**Comment by evanmiller** [comment]
The compression sas rle fuzzer is working as intended - the compression routines are single (large) functions so they will not trigger much coverage relative to the size of the code base. 

I would prefer a third approach where the OSS-Fuzz team updates the `check_build` script to use more intelligent heuristics.

**Comment by Google-Autofuzz** [comment]
Hi,

We reported the feature request internally.
For the time being, quickest is to add an exception in https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/test_all#L121 as part of the PR.

Does this work for you?

**Comment by inferno-chromium** [comment]
@evanmiller - we have filed https://github.com/google/oss-fuzz/issues/2469 to track this, but at this point, we don't have ideas to implement this. we need some way to detect uninstrumented sanitizer code, without looking at total edge count. if you have ideas, please feel free to add it there.

we want to get your fuzzers running soon, so i have added the fuzz target exception in https://github.com/google/oss-fuzz/commit/4d3073292ae43d99b1bd34b58e45021cb83760ae. can you try running check_build again and see if everything passes. then please submit the PR to enable these fuzzers.

**Comment by evanmiller** [comment]
Many are still failing, I will open a PR with the ones that work.

Would it be possible to create more edges by enabling `trace-cmp`? The failing fuzzers tend to have large switch statements.

**Comment by inferno-chromium** [comment]
@kcc - thoughts here ? these are small targets, should we be blacklisting like https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/test_all#L121 or do you have any other ideas ?

**Comment by Dor1s** [comment]
Just echoing my comment from https://github.com/google/oss-fuzz/issues/2469#issuecomment-497069346, very small fuzz target are almost useless, so options are:

1) extend the functionality under test
2) combine several targets into one
