### ISSUE TITLE
Numeric values in SPSS .por file converted as infinite values (inf)

### ISSUE THREAD

**Issue by briatte** [WizardMac/ReadStat#182]
I am using [this `.por` file](https://www.europeansocialsurvey.org/download.html?file=ESS1_FR_SDDF&c=FR&y=2002&loggedin), which can also be temporarily downloaded at [this address](https://f.briatte.org/temp/ess-sddf-test/ESS1_FR_SDDF.por).

Converting to CSV using a freshly-compiled version of `readstat-1.0.1` yields this:

```
$ head ~/Downloads/ESS1_FR_SDDF.spss/ESS1_FR_SDDF.csv
"IDNO","CNTRY","PSU","SAMPPOIN","STRATIFY","PROB"
10001.000000,"FR",130.000000,,"",inf
10002.000000,"FR",401.000000,,"",inf
10003.000000,"FR",108.000000,,"",inf
10004.000000,"FR",711.000000,,"",inf
10005.000000,"FR",102.000000,,"",inf
10006.000000,"FR",404.000000,,"",inf
10007.000000,"FR",623.000000,,"",inf
10008.000000,"FR",908.000000,,"",inf
10009.000000,"FR",909.000000,,"",inf
```

The problem is in the `PROB` column, which, when correctly parsed, should read as follows (using the `foreign` package in R):

```
# > head(foreign::read.spss("https://f.briatte.org/temp/ess-sddf-test/ESS1_FR_SDDF.por", to.data.frame = TRUE))
   IDNO CNTRY PSU SAMPPOIN STRATIFY         PROB
1 10001    FR 130       NA          1.651397e-05
2 10002    FR 401       NA          8.236820e-07
3 10003    FR 108       NA          1.651397e-05
4 10004    FR 711       NA          7.193571e-06
5 10005    FR 102       NA          5.061940e-07
6 10006    FR 404       NA          2.532250e-07
```

The problem logically also affects the R binding for ReadStat, `haven`. I'll cross-post the issue there.

The issue was detected while working on [this discussion about the `essurvey` R package](https://github.com/ropensci/essurvey/issues/9).

**Comment by evanmiller** [comment]
Thanks for the report. Fixed in dev branch.

**Comment by briatte** [comment]
Thanks a lot, ReadStat rocks!
