### ISSUE TITLE
seg fault when writing por file

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/ReadStat#184]
I'm trying to write a simple por file by just adapting writeEx (my adaptation is attached). The program compiles but when running I get a seg fault. I think the problem comes from the function por_write_double_to_buffer in line 109 of readstat_por_write.c: string[offset++] = '0'; because at this point string is a null pointer ((gdb) p string[0]
Cannot access memory at address 0x0). Am I initializing or doing something in the wrong way?
 
if using the command line application to convert an xpt to por (the xpt to csv works well):

```
$ bin/bin/readstat haven.xpt haven.por
Error beginning row: A provided name contains an illegal character
Converted 1 variables and 1 rows in 0.00 seconds
Error processing haven.xpt: The parsing was aborted (callback returned non-zero value)
```
attached the writeEx.c and haven.xpt

[write_por.zip](https://github.com/WizardMac/ReadStat/files/3310549/write_por.zip)

**Comment by ofajardo** [comment]
Thanks for the explanation. 

I guess that means I should just convert all variable names to uppercase? (Easy to do on my side). Are there other forbidden characters?

In the Readstat command line app btw the conversion fails as well with the same error message, as I reported. Does that mean you're expecting the user to convert variable names to Uppercase themselves before converting? (It sounds to me as if the readstat command line app should do that). Not very important, just an observation.

**Comment by evanmiller** [comment]
Hi @ofajardo,

Yes, the library is conservative and leaves it to the client to decide how to do the conversion. 

The command-line tool should probably attempt a conversion.

You can see the validation logic here:

https://github.com/WizardMac/ReadStat/blob/master/src/spss/readstat_por_write.c#L341

**Comment by ofajardo** [comment]
hi @evanmiller 

Thanks! that solves my issues, now I have implemented writing por files in pyreadstat. I will therefore close this issue.

On a small side note in case you are interested, I can write a note (with readstat_add_note) to a por file and later I can read it with Readstat. However SPSS 25 does not read that note (just appears emtpy).

**Comment by evanmiller** [comment]
> On a small side note in case you are interested, I can write a note (with readstat_add_note) to a por file and later I can read it with Readstat. However SPSS 25 does not read that note (just appears emtpy).

Please open a new issue describing the bug in detail. Thanks.

**Comment by ofajardo** [comment]
> Please open a new issue describing the bug in detail. Thanks.

I have done one more test: I have a sav file produced in SPSS with notes. I save it as POR in SPSS. The resulting POR also does not have the note anymore. So it seems that POR files do not support notes (?). So in such case I guess there is nothing really to be repaired, although it is a bit odd that you can write read and write notes with Readstat but not with SPSS. 
In Pyreadstat I will just not allow notes to be written for POR files. 
Let me know if you still would like to have an issue about this.

**Comment by evanmiller** [comment]
I am following the spec here:

https://www.gnu.org/software/pspp/pspp-dev/html_node/Portable-File-Document-Record.html#Portable-File-Document-Record

Each "note" is a <80 character line in the document record. I'm not sure what SPSS is up to!

**Comment by ofajardo** [comment]
Oh I see. OK thanks for the clarification! 
I think there is nothing to report then.
