### ISSUE TITLE
No rule to make target 'man/readstat.man'

### ISSUE THREAD

**Issue by peiyaoli2** [WizardMac/ReadStat#188]
Hi! When I build on windows with mingw64, I ran into this during `make`:
`make: *** No rule to make target 'man/readstat.man', needed by 'all-am'.  Stop.`
This happens after `CCLD readstat.exe`.

(I don't think I ran into this issue the last time I built on mingw64, back in May or June)

Edit: I tried building on mac and the issue doesn't occur on mac, does anyone have any idea why this is happening to windows?

**Comment by evanmiller** [comment]
Hi, to debug this I will need the surrounding output, ReadStat version, and mingw64 version.

ReadStat 1.1.4 builds fine under mingw64 using Appveyor:

https://ci.appveyor.com/project/evanmiller/readstat/branch/master/job/lvc7bd6dagcrg3s6

**Comment by peiyaoli2** [comment]
Hi! I haven't run into this issue recently, so I will close this.
