### ISSUE TITLE
Windows install instructions

### ISSUE THREAD

**Issue by groliver-pcci** [WizardMac/ReadStat#189]
There appears to be a typo:

pacman -S autoconf automake libtool mingw-w64-x86_64-toolchain **ingw**-w64-x86_64-cmake mingw-w64-x86_64-libiconv
>> replace to
pacman -S autoconf automake libtool mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-libiconv

Also for slow connection time out issues consider adding flag to remove timeout errors
 --disable-download-timeout

**Comment by evanmiller** [comment]
Thanks, will fix
