### ISSUE TITLE
Stata C API support

### ISSUE THREAD

**Issue by wbuchanan** [WizardMac/ReadStat#19]
For the sake of consistency, wouldn't it make sense to incorporate Stata's C API header file to define the data types?  

http://www.stata.com/plugins/stplugin.h
http://www.stata.com/plugins/stplugin.c

I would think it could help with future releases and make the data types a bit easier to handle.

**Comment by evanmiller** [comment]
Thanks for the suggestion. Without license information in those files I don't think I'll be able to incorporate them into the project. I also don't think they'd add a lot of value at this point.
