### ISSUE TITLE
Windows Build instructions incorrect

### ISSUE THREAD

**Issue by pds2208** [WizardMac/ReadStat#190]
The Windows specific notes has 2 errors; one spelling mistake and make is needed to, eh, make

> pacman -S autoconf automake libtool mingw-w64-x86_64-toolchain ingw-w64-x86_64-cmake mingw-w64-x86_64-libiconv

should be

> pacman -S autoconf automake libtool mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-libiconv make

**Comment by evanmiller** [comment]
Duplicate of #189

**Comment by pds2208** [comment]
Thanks but the make command still needs to be installed on windows as above.

**Comment by evanmiller** [comment]
Thanks, will fix
