### ISSUE TITLE
Some sas7bdat files are read incorrectly (the columns aren't being parsed right)

### ISSUE THREAD

**Issue by mirhyman** [WizardMac/ReadStat#198]
Problem: I have attached the problem file, along with a screenshot of what the expected values should be. 

When reading the attached file, some of the columns data are garbled. I went ahead and tried to debug through using this spec https://cran.r-project.org/web/packages/sas7bdat/vignettes/sas7bdat.pdf and I think maybe part of the problem is the column_offset being miscalculated for certain columns (not certain though because it seems like it must not be off by much and it only happens for this file).

I reproduced this bug by reading and then exporting the sas7bdat file to a csv file. I then compared the output with similar sas7bdat files (made by the same OS/sas7bdat version etc), and the attached file was the only one with a problem.

Problem file:
[staples_test1.zip](https://github.com/WizardMac/ReadStat/files/4100473/staples_test1.zip)
Output files (expected and actual):
[test.zip](https://github.com/WizardMac/ReadStat/files/4100511/test.zip)

**Comment by evanmiller** [comment]
Thanks. To be clear - is it only the first 18 rows in the test file that appear to be affected?

By the way, it looks like the provided expected vs actual have very different numbers of rows (1000 rows vs 54,860).

**Comment by evanmiller** [comment]
Okay, I think I found the issue - this is now fixed in the `dev` branch.

**Comment by mirhyman** [comment]
Hi! Thanks for the fix -- sorry for the lack of responding, I found all of these email notifications in my spam folder. I will test it out with the fix in the dev branch thanks!

**Comment by mirhyman** [comment]
Seems to work thanks!
