### ISSUE TITLE
Error 5 on certain sas7bdat files

### ISSUE THREAD

**Issue by quantbabies** [WizardMac/ReadStat#20]
The library gives an error 5 for certain (very large) sas7bdat files.  I haven't been able to pin down the problem myself.  Files can be read with https://pypi.python.org/pypi/sas7bdat

Any tips on the kinds of issues I should be thinking about?

**Comment by evanmiller** [comment]
Are the files compressed? Currently we don't support BINARY compression.

**Comment by quantbabies** [comment]
Here's the header from the python package sas7bdat

	col_count_p1: 10
	col_count_p2: 0
	column_count: 10
	compression: None
	creator: None
	creator_proc: CONNECT
	date_created: 2009-10-10 13:16:16.041934
	date_modified: 2009-10-10 13:16:16.041934
	endianess: little
	file_type: DATA
	filename: somedata.sas7bdat
	header_length: 8192
	lcp: 7
	lcs: 0
	mix_page_row_count: 87
	name: somedata.sas7bdat
	os_name: x86_64
	os_type: 2.6.18-92.1.22.e
	page_count: 2987773
	page_length: 8192
	platform: unix
	row_count: 433226881
	row_length: 56
	sas_release: 9.0201M0
	server_type: Linux
	u64: True

**Comment by evanmiller** [comment]
Do you have a (smaller) file you can send me that demonstrates the problem? Since it's a general parse error I have no idea what the problem might be. (Use `readstat_error_message` to convert the error code to a string.)

**Comment by quantbabies** [comment]
I wish I could share.  If you are interested, I have dug in a bit.  I apologize for no line numbers, I've made a few changes to the code. 

One file reads fine until near the end of the file at which point it sets retval = READSTAT_ERROR_PARSE just after the declaration of sas_parse_catalog_page near line 700 readstat_sas.c

The second file doesn't read at all.  It sets retval = READSTAT_ERROR_PARSE near like 860 of readstat_sas.c

      if (len > 0 && compression != SAS_COMPRESSION_TRUNC) {
            if (offset > page_size || offset + len > page_size ||
                    offset < off+24+subheader_count*lshp) {
                retval = READSTAT_ERROR_PARSE;
                printf("Foobar 19");
                /*
                goto cleanup;
                */
At this point compression = 64, but the file is not compressed (at least according to the python package, which does not call either of its decompression algorithms when reading the file).

**Comment by evanmiller** [comment]
I received similar reports from other users and was able to track down the issue. An integer overflow was producing a negative offset in the file, which caused things to go haywire at around the 2GB mark. This commit ought to fix it:

https://github.com/WizardMac/ReadStat/commit/1bae419a277c5f81aa84427e68a17b406a62d263

**Comment by quantbabies** [comment]
Even after making the edits in that commit, I still get error number 5 on a <400mb file.  It happens at the last line, and is tripped in readstat_sas.c at "foobar 10"

static readstat_error_t sas_parse_subheader(uint32_t signature, const char *subheader, size_t len, sas_ctx_t *ctx) {
    readstat_error_t retval = READSTAT_OK;

    if (len < 6) {
        retval = READSTAT_ERROR_PARSE;
        printf("%s","foobar 9");
        goto cleanup;
    }
    if (signature == SAS_SUBHEADER_SIGNATURE_ROW_SIZE) {
        retval = sas_parse_row_size_subheader(subheader, len, ctx);
    } else if (signature == SAS_SUBHEADER_SIGNATURE_COLUMN_SIZE) {
        retval = sas_parse_column_size_subheader(subheader, len, ctx);
    } else if (signature == SAS_SUBHEADER_SIGNATURE_COUNTS) {
        /* void */
    } else if (signature == SAS_SUBHEADER_SIGNATURE_COLUMN_TEXT) {
        retval = sas_parse_column_text_subheader(subheader, len, ctx);
    } else if (signature == SAS_SUBHEADER_SIGNATURE_COLUMN_NAME) {
        retval = sas_parse_column_name_subheader(subheader, len, ctx);
    } else if (signature == SAS_SUBHEADER_SIGNATURE_COLUMN_ATTRS) {
        retval = sas_parse_column_attributes_subheader(subheader, len, ctx);
    } else if (signature == SAS_SUBHEADER_SIGNATURE_COLUMN_FORMAT) {
        retval = sas_parse_column_format_subheader(subheader, len, ctx);
    } else if (signature == SAS_SUBHEADER_SIGNATURE_COLUMN_LIST) {
        /* void */
    } else {
        retval = READSTAT_ERROR_PARSE;
        printf("%s","foobar 10");
    }

**Comment by quantbabies** [comment]
Even after making the edits in that commit, I still get error number 5 on a <400mb file. It happens at the last line, and is tripped in readstat_sas.c at "foobar 10"

static readstat_error_t sas_parse_subheader(uint32_t signature, const char *subheader, size_t len, sas_ctx_t *ctx) {
readstat_error_t retval = READSTAT_OK;

if (len < 6) {
    retval = READSTAT_ERROR_PARSE;
    printf("%s","foobar 9");
    goto cleanup;
}
if (signature == SAS_SUBHEADER_SIGNATURE_ROW_SIZE) {
    retval = sas_parse_row_size_subheader(subheader, len, ctx);
} else if (signature == SAS_SUBHEADER_SIGNATURE_COLUMN_SIZE) {
    retval = sas_parse_column_size_subheader(subheader, len, ctx);
} else if (signature == SAS_SUBHEADER_SIGNATURE_COUNTS) {
    /* void */
} else if (signature == SAS_SUBHEADER_SIGNATURE_COLUMN_TEXT) {
    retval = sas_parse_column_text_subheader(subheader, len, ctx);
} else if (signature == SAS_SUBHEADER_SIGNATURE_COLUMN_NAME) {
    retval = sas_parse_column_name_subheader(subheader, len, ctx);
} else if (signature == SAS_SUBHEADER_SIGNATURE_COLUMN_ATTRS) {
    retval = sas_parse_column_attributes_subheader(subheader, len, ctx);
} else if (signature == SAS_SUBHEADER_SIGNATURE_COLUMN_FORMAT) {
    retval = sas_parse_column_format_subheader(subheader, len, ctx);
} else if (signature == SAS_SUBHEADER_SIGNATURE_COLUMN_LIST) {
    /* void */
} else {
    retval = READSTAT_ERROR_PARSE;
    printf("%s","foobar 10");
}

**Comment by evanmiller** [comment]
Are you using the latest code? That code snippet looks out of date. I've made additional fixes in the last month which may resolve the issue for you.
