### ISSUE TITLE
Readstat cannot open file where the filepath contains non-unicode characters

### ISSUE THREAD

**Issue by mirhyman** [WizardMac/ReadStat#200]
I have a file that is named with Icelandic characters and on Windows (I don't know about other OS's but I can test them if relevant) when I try to read the file using readstat I get an "unable to read file" error. I can work around this by just changing the filepath to not contain icelandic characters but ideally it would be able to work without that. 

I also tested this using japanese characters in the filepath, as well as korean to verify it was not just icelandic character problems. 

I have attached a simple repro with an icelandic and japanese file name path:

[新しいフォルダー 2.zip](https://github.com/WizardMac/ReadStat/files/4489358/2.zip)
[Ö.zip](https://github.com/WizardMac/ReadStat/files/4489363/O.zip)

**Comment by evanmiller** [comment]
Thanks for the report. I do not see the bug on macOS. It would help to have more details about the system (file system type, OS version, build environment).

**Comment by ofajardo** [comment]
Just in case it is of any help, we had the issue on pyreadstat and we solved it with @jonathon-love : 
https://github.com/Roche/pyreadstat/issues/12

**Comment by mirhyman** [comment]
I just verified this does not repro on Mac (I have a linux centOS box but I would need to do some work to get it running with this), only on Windows so the special open handler for windows might be what helps on this one.

**Comment by peiyaoli2** [comment]
@ofajardo @jonathon-love 
Would it be possible for you two to add the non-unicode filepath support changes to this project as well? That would be greatly appreciated!

**Comment by jonathon-love** [comment]
yup. some MSVC support has been added to the project recently, and so we should be able to add support for this shortly.

cheers

**Comment by zebrys** [comment]
This bug should be fixed now.  @mirhyman @jonathon-love do you confirm this ?

**Comment by peiyaoli2** [comment]
Yes, can confirm that it works. Thanks so much! @zebrys
