### ISSUE TITLE
timestamp string invalid in Sav file

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/ReadStat#203]
hi

Similar thing as #197, but different file: trying to open it throws: The file's timestamp string is invalid.

[invalid_string.zip](https://github.com/WizardMac/ReadStat/files/4640487/invalid_string.zip)

**Comment by evanmiller** [comment]
This is not an SPSS file. It appears to be another proprietary format. I will add a more helpful error message in cases like this.

**Comment by ofajardo** [comment]
Thanks!

**Comment by ofajardo** [comment]
Just for the records, it seems it is an IDL file.
