### ISSUE TITLE
passing argument 2 of 'libiconv' from incompatible pointer type

### ISSUE THREAD

**Issue by hadley** [WizardMac/ReadStat#204]
In R CMD checks on windows only, I see:

```
  readstat/readstat_convert.c:18:42: warning: passing argument 2 of 'libiconv' from incompatible pointer type [-Wincompatible-pointer-types]
  src/spss/readstat_sav_parse.rl:89:17: warning: passing argument 2 of 'libiconv' from incompatible pointer type [-Wincompatible-pointer-types]
  src/spss/readstat_sav_parse.rl:197:17: warning: passing argument 2 of 'libiconv' from incompatible pointer type [-Wincompatible-pointer-types]
```

I'll look into this from the R side, but has anything changed here recently on the ReadStat side?

**Comment by hadley** [comment]
Oh, I bet it's this: https://github.com/WizardMac/ReadStat/commit/b5a23087b813e06b5f30a41e2b8cfa89823ef874#diff-d517b55acd07dac342f889f7970bbf7d

haven doesn't call autoconf so this doesn't get set automatically; presumably I should be setting myself somewhere.

**Comment by hadley** [comment]
But that changed in Feb 2019, but my failure is more recent. Doing a little spelunking on my github actions suggests this started failing for me when I switched my windows tests to use R 4.0 (instead of 3.6). R 4.0 presumably is activating stricter tests.

**Comment by hadley** [comment]
Same problem with R + libxls — https://github.com/libxls/libxls/pull/19

**Comment by evanmiller** [comment]
Thanks for the report. Autoconf is the one and only supported build environment for this project; as much as I appreciate what haven has done for ReadStat, it's simply outside the scope of ReadStat to support the kind of copy-pasted code builds that you're asking about.

I'm happy to accept a patch that will facilitate things on your end, but in the meantime the warning does not affect Readstat per se and thus I am not going to spend time debugging it.

If R builds allow for static linking maybe we can explore something in that direction (I.e. build a static archive with Autoconf and then statically link it when haven is compiled).

**Comment by hadley** [comment]
Yeah, I think it makes the most sense for me to just manually set the flag on windows.
