### ISSUE TITLE
readstat won't write a .sav file with a variable named `ותק_ב` correctly

### ISSUE THREAD

**Issue by jonathon-love** [WizardMac/ReadStat#206]
hi evan,

with a bit of help from @ofajardo, over at https://github.com/jamovi/jamovi-readstat/issues/5 we've managed to narrow down an issue with writing .sav files with readstat, with a particular variable name. [here is a minimal reproducible example](https://github.com/WizardMac/ReadStat/files/4695160/hebrew.csv.zip).

the file writes without error (in pyreadstat, haven, and jamovi), but can't be read (in pyreadstat, haven, jamovi, or spss). it gives the error:

`Invalid file, or file has unsupported features.`

with thanks

**Comment by ofajardo** [comment]
another strange thing is that if one opens that csv I generated in an editor (Geany) you see ותק_ב but if you do a head on ubuntu, or reading the file in python you see something else:

![image](https://user-images.githubusercontent.com/17498727/83136166-4f818800-a0e7-11ea-8164-2053b3f6a49f.png)

Other strange observations are that this variable name is part of a longer one, but the minimal set of characters to reproduce the issue. If the first or last character is removed, then it's good. If the 4th character (underscore) is removed, then it is also fine.

**Comment by ofajardo** [comment]
Ah ok the difference between text editor/ git and head/python is probably only reading it from right to left or left to right

**Comment by evanmiller** [comment]
@jonathon-love Can you please provide the SAV file in your reproducible example? Thanks

**Comment by jonathon-love** [comment]
here 'tis,

i've just checked and this *does* open correctly in spss, so it's possible there's nothing wrong with the write procedure, and it's the read procedure which is the issue.

[hebrews.sav.zip](https://github.com/WizardMac/ReadStat/files/4708662/hebrews.sav.zip)

with thanks

**Comment by evanmiller** [comment]
Notes for myself:

```
$ readstat ~/Downloads/hebrews.sav
Format: SPSS binary file (SAV)
Error parsing string "ותק_�=ותק_ב" around byte #8/18, character =
Error processing ~/Downloads/hebrews.sav: Invalid file, or file has unsupported features
```

The long variable label record (which ReadStat is choking on) contains `key=value` pairs. Keys are limited to 8 bytes; in this file, the key is truncated inside of a multi-byte character, leaving an invalid string as the key.

Two possible solutions: 1) Modify the writer to truncate at multi-byte character boundaries, rather than the 8 byte mark  2) Modify the reader to accept invalid / incomplete sequences in the "key" field, and possibly in other places in the reader code.

It would be useful to know how SPSS and other software handle this particular multi-byte issue.

**Comment by jonathon-love** [comment]
this is what it looks like in spss:

<img width="535" alt="Screen Shot 2020-06-02 at 11 08 14" src="https://user-images.githubusercontent.com/3240247/83468864-634f3480-a4c1-11ea-9e3d-534baf5ea691.png">

**Comment by evanmiller** [comment]
@jonathon-love Since SPSS reads the file correctly, I have modified the read side rather than the write side. Please try the latest commit in the dev branch.

**Comment by ofajardo** [comment]
works nicely in pyreadstat

**Comment by ofajardo** [comment]
just in case, I checked the data [here](https://github.com/tidyverse/haven/issues/467) and indeed it produces an error in pyreadstat before the change here, but it is fine after the last Readstat commit.

**Comment by jonathon-love** [comment]
yup, works for me too. thanks evan.
