### ISSUE TITLE
Readstat not reading XPT v8 column names correctly

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/ReadStat#208]
When trying to read the attached XPT file v8 readstat is not reading the column names correctly. 

This is what readstat is reading (only first row included for brevity)
```
./readstat dates_8.xpt -
"dt","dt","timezone","dates","string_dates","times","string_times","seconds","seconds"
-86401.000000,"1959-12-30 23:59:59","UTC",-2.000000,"1959-12-30",86399.000000,"23:59:59",-86401.000000,1.000000
```

and it should be:

```
'dt', 'string_dt', 'timezone', 'dates', 'string_dates', 'times', 'string_times', 'seconds', 'missings'
```

@reikoch is aware of the issue, according to him this comes from the fact the XPT has labels.
The XPT files was originated from a sas7bdat files also attached. 

[dates.zip](https://github.com/WizardMac/ReadStat/files/5123985/dates.zip)

**Comment by ofajardo** [comment]
Another detail:

* If reading the sas7bdat with readstat, then saving it to a XPT v8 with readstat, the file can be read again with readstat (and also SAS and all is OK).
* If saving it to a XPT v5, then a similar issue as described before is seen

**Comment by evanmiller** [comment]
Try this https://github.com/WizardMac/ReadStat/commit/6122c01865541befb0487bdc4c613a4e69c4d0b0

**Comment by ofajardo** [comment]
it works! 

thanks!

**Comment by evanmiller** [comment]
@ofajardo Thanks for letting me know. I have put together a release candidate with all of the latest changes:

https://github.com/WizardMac/ReadStat/releases/tag/v1.1.4-rc0

If everything looks okay I will make an official release in a week or so.

**Comment by ofajardo** [comment]
Great, thanks!
