### ISSUE TITLE
Sav variable display width becomes 0 if string variables longer than 255 characters

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/ReadStat#210]
I am using readstat_variable_set_display_width to set the variable display width when writing a sav file. It is working, meaning when reading the written file I can get the display variable width with readstat_variable_get_display_width and it looks correct.

However if the dataset contains a value which is a string with 256 characters or more, writing it and reading again, then when using readstat_variable_get_display_width I get 0, interestingly not only for the variable containing the long string, but for any other variable in the dataset. 

The long string itself is read correctly.

**Comment by evanmiller** [comment]
Thank you for the report. Please try https://github.com/WizardMac/ReadStat/commit/03ba85c762d37da6961e6f88aaa52a3cb1ead256

**Comment by ofajardo** [comment]
it works! thanks!

Just one more question: it seems that the max value is 255, if I enter something higher it goes back to 255. Is that intentional?

**Comment by ofajardo** [comment]
Readstat is following the file specification given by PSPP, DATE and DATETIME are specifiied:

https://www.gnu.org/software/pspp/pspp-dev/html_node/Variable-Record.html

**Comment by evanmiller** [comment]
The display width is stored in two separate places. In the "legacy" location the width is limited to 255. In the new location there is no limit. I will need to tinker with it some more to make sure the proper location is used.

**Comment by evanmiller** [comment]
Can you provide a test case and ensure you are using the latest code? My tests pass using display widths of e.g. 1000.

**Comment by ofajardo** [comment]
hmm, attached the python script I am using, and the resulting file, setting it to 1000 and I recover 255 from readstat_variable_get_display_width (I am also printing the call to readstat_variable_get_display_width internally, not in the script). 
PSPP in the other hand says it is correct (1000) ... so now I am confused 

[Archive.zip](https://github.com/WizardMac/ReadStat/files/5143075/Archive.zip)

**Comment by evanmiller** [comment]
Try this https://github.com/WizardMac/ReadStat/commit/3fe313f6d9bee0c062fe74199f474c6c8bd16106

It looks like the display record was not being read correctly with long strings. I didn't notice this before because the function's return value was never checked (and short strings were fine).

**Comment by ofajardo** [comment]
yes, that fully solves it!

thanks!
