### ISSUE TITLE
Reading Sav file gives back empty strings

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/ReadStat#212]
Reading the attached file gives empty strings in the second column, when according to the author it should give some chinese characters:

```
"Respondent_Serial","Respondent_Serial_SourceFile"
8.000000,""
25.000000,""
34.000000,""
47.000000,""
48.000000,""
```

[test1.zip](https://github.com/WizardMac/ReadStat/files/5167753/test1.zip)

thanks!

**Comment by evanmiller** [comment]
What is the expected output?

**Comment by ofajardo** [comment]
Waiting for user input on that.

I opened it in SPSS and got empty strings as well. But it has failed in the past to read non latin charachters, so let's see if the reporter if the issue clarifies.

**Comment by evanmiller** [comment]
Since ReadStat agrees with SPSS then I am closing the issue.

I appreciate all of your contributions - however in the interest of avoiding clutter, please wait until you have evidence of a bug before opening a new issue here. Thanks!

**Comment by ofajardo** [comment]
Yep, I agree, sorry for this one!
