### ISSUE TITLE
More robust handling of not-well-formatted files

### ISSUE THREAD

**Issue by jonathon-love** [WizardMac/ReadStat#217]
hi evan,

i had some people contact me about the spss files they were writing, not being able to be read by jamovi (and by extension, readstat ... or is it the other way around?), however, these files could be read by spss. the error message was:

`Error parsing string "Var1=Var1    Var2=Var2    Var3=Var3    Var4=Var4    Var5=Var5    Q1=Q1" around byte #1/55, character a`

i believe the error is the `a` in `Var1=` ... where i think ReadStat expects the name before the `=` to be all uppercase (and i think spss automagically 'upgrades' these to be uppercase if you open and resave the file).

am i correct in what i'm thinking?

which leads to a follow-up question ... what about ReadStat handling these files the same way spss does?

with thanks

**Comment by evanmiller** [comment]
Hi, it would help to have an example file demonstrating the issue that I can test against. Thanks.

**Comment by jonathon-love** [comment]
[sav files.zip](https://github.com/WizardMac/ReadStat/files/5295572/sav.files.zip)

with thanks

**Comment by evanmiller** [comment]
@jonathon-love Please try the `dev` branch

**Comment by jonathon-love** [comment]
all good. thanks evan!
