### ISSUE TITLE
How to build with libxlsxwriter and zlib for Windows under MSYS?

### ISSUE THREAD

**Issue by User-3090** [WizardMac/ReadStat#218]
Title says it all. I could not figure out how to get it to recognize libxlsxwriter during configure / make. Any hints highly appreciated.

Also maybe add

./configure CFLAGS="-static"
make LDFLAGS="-all-static"

to create static single binaries for Windows in AppVeyor.

Thanks a lot for creating this awesome tool!

**Comment by evanmiller** [comment]
Hi, do you have zlib / libxlsxwriter development headers installed? Often there is a separate -devel package if you are using a package manager.
