### ISSUE TITLE
Update ReadStat version in VS17 PropertySheet.props

### ISSUE THREAD

**Issue by curtisalexander** [WizardMac/ReadStat#227]
@evanmiller While you are performing updates on the Windows side, you may want to update the `ReadStat` version to `1.1.5`  (or `1.1.6` for the next version) within the [PropertySheet.props](https://github.com/WizardMac/ReadStat/blob/master/VS17/PropertySheet.props#L8) file in the `VS17` directory.

**Comment by evanmiller** [comment]
Thanks, will make a note of it!

**Comment by curtisalexander** [comment]
Closed by 67be6f5a255eda6b001259a5f53e8333568a380b
