### ISSUE TITLE
SAS file working previously fails with unsuported features error

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/ReadStat#232]
hi

The attached sas7bdat file was read correctly with an older version of Readstat (1.1.0), while now (version 1.1.5 and 1.1.6 RC0) it is giving an error:

```
Invalid file, or file has unsupported features
```

thanks in advance!

original report: https://github.com/Roche/pyreadstat/issues/117

[DCSKINPRODUCT.sas7bdat.zip](https://github.com/WizardMac/ReadStat/files/6121985/DCSKINPRODUCT.sas7bdat.zip)

**Comment by evanmiller** [comment]
Thanks for the report. Bisecting reveals the offending commit is:

https://github.com/WizardMac/ReadStat/commit/ede520eb3a11cff167307fb06de96d9d94bee34d

Before the above commit, non-conforming version strings were accepted, but this was changed to prevent certain non-deterministic behavior.

Examining the file, it looks like the software version string is `V.0304M0`. ReadStat is expecting the first character to be a digit. Looking at the original report, it appears the data set was generated by "SAS Visual Forecasting". So maybe the `V` is for "Visual"? In any event, the code needs to be updated to account for this possibility.
