### ISSUE TITLE
readstat_get_row_count returns -1 for xport

### ISSUE THREAD

**Issue by andreasnoack** [WizardMac/ReadStat#234]
It's being set in https://github.com/WizardMac/ReadStat/blob/69f55186ae615a14a3367ad5cd08b7829aa8f308/src/sas/readstat_xport_read.c#L259. Is it because the value isn't directly available in the file header? If so then it would be great to document the meaning of `-1`. I couldn't find any explanations for the value. From the source, it looks like it's `parsed_row_count` which is counting the number of rows as you go.

**Comment by evanmiller** [comment]
Yes - `-1` is intended as a sentinel value to indicate that the row count is not available in the file metadata. Happy to add a comment to the header file to this effect.
