### ISSUE TITLE
Possible regression in SAS parsing

### ISSUE THREAD

**Issue by hadley** [WizardMac/ReadStat#237]
[dua_one.sas7bdat.zip](https://github.com/WizardMac/ReadStat/files/6298670/dua_one.sas7bdat.zip) from https://github.com/btskinner/duawranglr/tree/master/tests/testthat/testdata

Dev version of haven with latest ReadStat:

``` r
haven::read_sas("~/Downloads/dua_one.sas7bdat")
#> ReadStat: Error parsing page 0, bytes 1024-5119
#> Error: Failed to parse /Users/hadley/Downloads/dua_one.sas7bdat: Invalid file, or file has unsupported features.
```

CRAN version of haven (with older ReadStat; can find exactly version if helpful):

``` r
haven::read_sas("~/Downloads/dua_one.sas7bdat")
#> # A tibble: 8 x 3
#>   level_i level_ii level_iii
#>   <chr>   <chr>    <chr>    
#> 1 sid     "sid"    "sid"    
#> 2 sname   "sname"  "sname"  
#> 3 dob     "dob"    ""       
#> 4 gender  ""       ""       
#> 5 raceeth ""       ""       
#> 6 tid     ""       ""       
#> 7 tname   "tname"  "tname"  
#> 8 zip     "zip"    ""
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by evanmiller** [comment]
Bisecting indicates the offending commit is:

https://github.com/WizardMac/ReadStat/commit/2a599d6ed37102298908c5d1a6bf7e77f39ff23f

I'll need to dig into it more to find out what's going on here.

**Comment by hadley** [comment]
Guessing from the context, it's possible that this file was ReadStat generated (via haven); so another possible explanation is that a previous version of ReadStat created an invalid file.

**Comment by evanmiller** [comment]
@hadley The official ReadStat policy remains "all generated SAS files are considered invalid," so I'm not sure if it's worth supporting old ReadStat-generated SAS files. Did this originate as user-generated report, or from an automated regression test?

**Comment by hadley** [comment]
Automated regression test.

**Comment by hadley** [comment]
I'll just do a PR to remove it from their tests.

**Comment by hadley** [comment]
Confirmed that they were created with haven, so closing this issue.
