### ISSUE TITLE
ReadstatError: Unable to convert string to the requested encoding (invalid byte sequence)

### ISSUE THREAD

**Issue by Bentlerman** [WizardMac/ReadStat#239]
Jupyter Notebook
3 panel stata files. Entries are mostly in English.

ph2009, meta = ps.read_dta('Philippines/Philippines-2009-full-data-.dta')
ph0915, meta = ps.read_dta('Philippines/Philippines_2009_2015.dta')
ph2015, meta = ps.read_dta('Philippines/Philippines-2015-full-data.dta')

I am able to read the 2009 file fine. Reading the other two give me an invalid byte sequence error. 

How would I resolve this?

[Enterprise Survey Datasets-20210312T090352Z-001.zip](https://github.com/WizardMac/ReadStat/files/6301158/Enterprise.Survey.Datasets-20210312T090352Z-001.zip)

**Comment by NilsEnevoldsen** [comment]
It appears to be due to a combination of a label with quotation marks and dta-format 115.

```stata
. dtaversion "Philippines-2015-full-data.dta"
  (file "Philippines-2015-full-data.dta" is .dta-format 115 from Stata 12)

. use "Philippines-2015-full-data.dta", clear

. save "dta-format-118.dta"

. label list EAL5S
EAL5S:
           1 AT LEAST ONE of the above 4 numbers is “Don’t know”
           2 ALL of the above 4 numbers have been provided

. label drop EAL5S

. saveold "no-eal5s-label.dta", version(12)
```

Haven then imports `dta-format-118.dta` and `no-eal5s-label.dta` correctly.

**Comment by Bentlerman** [comment]
Hey man, thank you for this! I do have stata actually, but I wanted to explore these datasets in pandas just to do some visualizations. I'll try using these new datasets and installing haven. : D

**Comment by NilsEnevoldsen** [comment]
Some more detail: DTA version 118 (Stata version 14+) is unicode; prior versions are not. In DTA versions 117 and below, "unicode" characters are transformed into their equivalent codepoints in ISO-8859-1 (or something similar, I'm not exactly sure).

So when readstat reads a single left quote, it's rendered as `â€˜`, a single right quote as `â€™`, and a left quote as `â€œ`. The trouble is with the right quote, `â€`, where `` is `009D`, the operating system command. I suspect this character trips up readstat.

Notably, Stata 16 imports and displays all of these symbols `‘’“”` in the expected way, even when importing a DTA version 117 and below.

**Comment by evanmiller** [comment]
Stata 13 and below do not record their encoding; it's up to the system to know or decide what the file encoding should be. Older versions of Stata typically used the system encoding (e.g. Windows-1252 in US and Western Europe).

From your description it sounds like these files are actually UTF-8 encoded, but ReadStat is treating them as Windows-1252. On the C side you can override this setting with:

```
readstat_set_file_character_encoding(parser, "UTF-8");
```

See

https://github.com/WizardMac/ReadStat/blob/69f55186ae615a14a3367ad5cd08b7829aa8f308/src/readstat.h#L372-L375

I'm not sure if the library you're using offers access to this setting or not.

**Comment by Bentlerman** [comment]
> @Bentlerman If you don't have access to Stata, I've resaved these files in a newer Stata format that I think readstat should import properly. Let me know if these work for you.
> 
> [Philippines.zip](https://github.com/WizardMac/ReadStat/files/6304378/Philippines.zip)

Hey Nils!

I tried opening it but I got this new error. 

[CODE]
ph2009, meta = ps.read_dta('ES Philippines/Philippines/Philippines-2009-full-data-.dta')
ph0915, meta = ps.read_dta('ES Philippines/Philippines/Philippines_2009_2015.dta')
ph2015, meta = ps.read_dta('ES Philippines/Philippines/Philippines-2015-full-data.dta')

[ERROR]
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-4-38448465b76f> in <module>
----> 1 ph2009, meta = ps.read_dta('ES Philippines/Philippines/Philippines-2009-full-data-.dta')
      2 ph0915, meta = ps.read_dta('ES Philippines/Philippines/Philippines_2009_2015.dta')
      3 ph2015, meta = ps.read_dta('ES Philippines/Philippines/Philippines-2015-full-data.dta')

pyreadstat\pyreadstat.pyx in pyreadstat.pyreadstat.read_dta()

pyreadstat\_readstat_parser.pyx in pyreadstat._readstat_parser.run_conversion()

pyreadstat\_readstat_parser.pyx in pyreadstat._readstat_parser.handle_value()

pyreadstat\_readstat_parser.pyx in pyreadstat._readstat_parser.convert_readstat_to_python_value()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 4: invalid continuation byte

**Comment by NilsEnevoldsen** [comment]
Hmm. Try passing the parameter `encoding='latin-1'` or `encoding='utf-8'` to `read_dta`?

**Comment by evanmiller** [comment]
Closing this issue – if you still are encountering problems, please raise them with pyreadstat first.
