### ISSUE TITLE
API Example

### ISSUE THREAD

**Issue by quantbabies** [WizardMac/ReadStat#25]
Can you update the sample implementation for the new API? In sample implementation, handle_value takes 5 inputs. In readstat.h readstat_value_handler takes 4 inputs. (There is an additional readstat_types_t in sample implementation. ) I assume there are other changes as well.

**Comment by evanmiller** [comment]
Thanks, updated:

https://github.com/WizardMac/ReadStat/commit/52dc5bb4ad4402894c24ad21f9d7914f0c008be9
