### ISSUE TITLE
Solaris compatibility

### ISSUE THREAD

**Issue by hadley** [WizardMac/ReadStat#250]
https://github.com/WizardMac/ReadStat/commit/8bfe4983798947b648204b408916360cefe73d93 broke solaris compatibility because Solaris [doesn't recognise values above 600](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#FOOT93). One alternative would be to copy libuv: https://github.com/libuv/libuv/pull/3152

**Comment by evanmiller** [comment]
Solaris compatibility is incidental at best... Happy to review a PR, but without access to a test machine it's a wontfix.

**Comment by hadley** [comment]
Yeah, totally fair. I have no interest in Solaris either, except that CRAN forces us to care. Here's the fix to haven that gets it working on solaris again (tested on [r-hub](https://builder.r-hub.io)): https://github.com/tidyverse/haven/commit/4a878a10a290a164c24f30edfb7e5192b1f15b1d. I can turn that into a PR to ReadStat if that looks good to you.

**Comment by evanmiller** [comment]
The example you linked also includes a `__sun` check... I'd be concerned about breaking or having weird linkage issues on other platforms unless the defines are air-tight.

Frankly, without an actual person trying to use the software on Solaris, I don't want to spend any mental energy on this.

**Comment by hadley** [comment]
Sure, understood!
