### ISSUE TITLE
Missing value support for integers in SPSS

### ISSUE THREAD

**Issue by gorcha** [WizardMac/ReadStat#251]
Another one from haven! :slightly_smiling_face:
From tidyverse/haven#596.

Currently missing value support for SPSS is limited to doubles and strings because of an explicit type check in the functions that write out the missing values info:
https://github.com/WizardMac/ReadStat/blob/a8e6705453f0e610a698a4d98b3dfa3087cf4b28/src/spss/readstat_sav_write.c#L244-L259
https://github.com/WizardMac/ReadStat/blob/a8e6705453f0e610a698a4d98b3dfa3087cf4b28/src/spss/readstat_sav_write.c#L346-L353

It seems like it should be OK to just use the double methods for all non-string values (since integers and 32 bit floats are all converted to doubles in SPSS output anyway) - it probably just needs a change to the conditional logic in these functions and maybe a couple of additional readstat_add_missing_* functions in here to deal with other types:
https://github.com/WizardMac/ReadStat/blob/a8e6705453f0e610a698a4d98b3dfa3087cf4b28/src/readstat_variable.c

I can chuck together a PR if you're happy with this approach?

**Comment by evanmiller** [comment]
From your perspective, would it be sufficient to change the `type` checks to:

```
if (readstat_variable_get_type_class(r_variable) == READSTAT_TYPE_CLASS_NUMERIC)
```

?

**Comment by gorcha** [comment]
Yep that's perfect, thank you!

**Comment by gorcha** [comment]
That works perfectly, thanks again
