### ISSUE TITLE
Hangs for large sas7bdat

### ISSUE THREAD

**Issue by quantbabies** [WizardMac/ReadStat#26]
Parses smallish files (on the order of 10mb) fine.  Simply hangs for larger (eg. 22gb) files.  Any idea what might be going on internally?  Data compresses nicely and I have a sample to share if you'd like.

**Comment by evanmiller** [comment]
A sample file would be great.

**Comment by BioStatMatt** [comment]
Swapping?

**Comment by quantbabies** [comment]
Shared a dropbox via email.

**Comment by evanmiller** [comment]
Got it. This should speed things up:

https://github.com/WizardMac/ReadStat/commit/2b8c161a0aebf4c6bd082fa278b58cddcc22c35e

**Comment by saurfang** [comment]
Just a quick thought: because sas7bdat is fixed length page based, the reading is easily parallelizable. I was successful implementing this using parso on Hadoop but I recognize it might be an overkill for an import task (presumably you don't import very often).

**Comment by evanmiller** [comment]
@saurfang I like the idea, but a parallel implementation probably isn't a great fit for this library, since the callbacks would have to worry about execution order and thread safety, and for large files you'd have to worry about disk contention.

**Comment by evanmiller** [comment]
@quantbabies Closing the issue -- please re-open if you still experience hangs.
