### ISSUE TITLE
row_limit performance issue

### ISSUE THREAD

**Issue by ankravch** [WizardMac/ReadStat#262]
I would expect the same performance to display first 1000 rows from two sas7bdat files that have the same schema but different number of rows.  But instead I observed:
```python
0.77 s to display first 1000 rows from sas7bdat with 164,407 rows 
133 s to display first 1000 rows from sas7bdat with 46,021,575 rows 
```
both sas7bdat files have the same schema.

**Comment by evanmiller** [comment]
Hi, parts of the logic require scanning the entire file before examining any of the row data. This may be optimized in the future but it is not a high priority.
