### ISSUE TITLE
Issues writing Stata StrL variables

### ISSUE THREAD

**Issue by gorcha** [WizardMac/ReadStat#269]
Hi!

While trying to add StrL support to haven (tidyverse/haven#584) we've noticed a couple of issues with the code for writing string refs.

### v,o indexing

The variable and observation numbers in the stata file should be indexed from 1, but ReadStat is indexed from 0. `readstat_insert_string_ref()` doesn't apply this, so we get an off by one in the variable and observation index values for the strLs. There's a simple fix for this:
```c
readstat_error_t readstat_insert_string_ref(readstat_writer_t *writer, const readstat_variable_t *variable, readstat_string_ref_t *ref) {
    if (!writer->initialized)
        return READSTAT_ERROR_WRITER_NOT_INITIALIZED;
    if (variable->type != READSTAT_TYPE_STRING_REF)
        return READSTAT_ERROR_VALUE_TYPE_MISMATCH;
    if (!writer->callbacks.write_string_ref)
        return READSTAT_ERROR_STRING_REFS_NOT_SUPPORTED;

    if (ref && ref->first_o == -1 && ref->first_v == -1) {
        ref->first_o = writer->current_row + 1;
        ref->first_v = variable->index + 1;
    }

    return writer->callbacks.write_string_ref(&writer->row[variable->offset], variable, ref);
}
```

### map offsets

All of the file offsets in the [map](https://www.stata.com/help.cgi?dta#map) in the file header are written in `readstat_begin_writing_data()`, but at this point the string refs are empty if they're being added row by row. Once the string refs are written out the file offsets for the sections after the strLs are different but the map isn't updated. The created file gives an `Invalid file, or file has unsupported features.` error.

I've confirmed that the issue is the offsets in the map - see the two files in [stata_strl.zip](https://github.com/WizardMac/ReadStat/files/8202582/stata_strl.zip):
* stata_strl.dta was written by haven via ReadStat (using the modified string ref insertion above for correct v,o values). The offsets for the sections after the `<strls>` are written as if this section is empty.
* In stata_strl_edit.dta I've manually edited the map with correct file offsets for the sections after the `<strls>` and this reads in successfully.

There's no support for non-sequential writing in the API at the moment so not sure how to get around this apart from populating the string refs before we begin writing rows.

**Comment by gorcha** [comment]
OK maybe jumped the gun a little on the map offsets!
It seems that the correct way to approach this is to add all of the string refs before we begin writing data.

So we:
* Add variables.
* `readstat_add_string_refs()` all the string refs in advance, and keep track of the returned ref pointer.
* Start writing rows and use `readstat_insert_string_refs()` with the references created earlier.

**Comment by gorcha** [comment]
And just a further note on the v,o indexing - the way it's currently setup is fine for roundtripping files in ReadStat, since it only cares if the v,o values in the strls table match the record that they map to, but it will likely cause issues in Stata since:
> (v,o) = (0,0) is a special allowed value that refers to a GSO containing
> an empty string ("") that is predefined for you (and that you must not
> redefine in the <strl>...</strl> table).

**Comment by evanmiller** [comment]
Looks like this is resolved, closing

**Comment by gorcha** [comment]
Yep with the off by one thingo fixed it's all good, thanks! 🙂
