### ISSUE TITLE
Number of rows in sas7bdat file nearly tripled

### ISSUE THREAD

**Issue by peiyaoli2** [WizardMac/ReadStat#283]
Hi, I have an SAS file in CJK characters, and in SAS Universal Viewer the number of rows is 42554. However readstat would give me 132252 rows (tested using both the python wrapper as well as the r wrapper, they both returned the same thing).

**Comment by dennisfisher** [comment]
Peiyao

This whole things seems odd.  The tibble shows 149K rows, whereas you report 132252.  I read the file with R:haven and it yielded 132242 rows.  That makes me suspect that the R output that you display is from a different SAS file.
Also, the entries in the first column of the two images do not match — again suggesting that you are reading different files.

Also, I assume that your assessment of the SAS file row # is coming from the highlighted text.  However, that reads 43046, not 42554.  

So, one possible explanation is that you are reading two separate files

Finally, there appears to be an issue displaying more than 10K lines in the Viewer — perhaps the viewer also has ab issue counting rows beyond 10L.

Dennis

Dennis Fisher MD
P < (The "P Less Than" Company)
Phone / Fax: 1-866-PLessThan (1-866-753-7784)
www.PLessThan.com <http://www.plessthan.com/>

**Comment by peiyaoli2** [comment]
Dennis - you are right, I think there are two versions of the file that was sent to me that got me confused. Either ways both version had very different # or rows in viewer vs. in readstat. Can you point me to the issue on Viewer that has trouble displaying more than 10k lines? Is it this https://communities.sas.com/t5/SAS-Visual-Analytics/I-need-to-show-more-than-40-000-rows/td-p/521464? Thanks!

**Comment by dennisfisher** [comment]
http://support.sas.com/kb/50/795.html
Problem Note 50795: SAS® Universal Viewer does not allow the number of rows option to be set above 10,000

also,
	https://support.sas.com/rnd/itech/doc9/dev_guide/reader/dsviewer.html


can you send images of the output from the same file from the Viewer and haven?


Dennis Fisher MD
P < (The "P Less Than" Company)
Phone / Fax: 1-866-PLessThan (1-866-753-7784)
www.PLessThan.com <http://www.plessthan.com/>

**Comment by peiyaoli2** [comment]
Dennis - Sorry about the mix-up, I have attached both versions of the file in this zip file:
[cpn_dailytrend_hist.zip](https://github.com/WizardMac/ReadStat/files/9538256/cpn_dailytrend_hist.zip)

They have the following number of rows in Viewer and haven:
![Screen Shot 2022-09-09 at 12 43 19 PM](https://user-images.githubusercontent.com/21374776/189431922-f566b2cd-6937-4cdf-976b-f217aa1a6173.png)
![Screen Shot 2022-09-09 at 12 46 59 PM](https://user-images.githubusercontent.com/21374776/189431933-6c50a3e5-3c18-4b5c-9f68-6cdcea2314ef.png)

**Comment by peiyaoli2** [comment]
Hi @dennisfisher - would you be able to either delete your comments or archive this issue so it's not public? I am waiting on confirmation on how to share for investigation.
