### ISSUE TITLE
Unable to parse sas7bdat when data set page size >= 16MB

### ISSUE THREAD

**Issue by gorcha** [WizardMac/ReadStat#286]
Related to #249 - we've had a bug report in haven (tidyverse/haven#697) from a user attempting to read a sas7bdat file with a 16 MiB (16777216 bytes) page size.

Assuming it needs a change like f6766cd2653338a26333a34982a6c023b4a987fc to allow the larger page size.

Thanks!

**Comment by evanmiller** [comment]
Thanks. As the OP discovered, the buffer memory limit was slightly less than 16MiB. I have raised it to be exactly 16MiB.

**Comment by gorcha** [comment]
Thanks, much appreciated!
