### ISSUE TITLE
`sprintf()` -> `snprintf()`

### ISSUE THREAD

**Issue by hadley** [WizardMac/ReadStat#292]
CRAN is starting crack down on use of `sprintf()` instead of `snprintf()` so this would be useful for us.

**Comment by evanmiller** [comment]
Is it just these three or are there other kinds of forbidden invocations?

https://github.com/search?q=repo%3AWizardMac%2FReadStat%20sprintf&type=code

**Comment by hadley** [comment]
Yeah, those were all I saw. Thanks!
