### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by hadley** [WizardMac/ReadStat#3]
It might be useful to have a version number so that it's easy to check when a binding is out of date

**Comment by evanmiller** [comment]
Yes having versions and formal releases would make sense. Relatedly, we should also tag the code for different version numbers.

**Comment by hadley** [comment]
Maybe once we get all the cross-platform stuff worked out it would be worthwhile to do a formal release.

**Comment by jar1karp** [comment]
This is probably now possible using autotools. Currently configure.ac sets the version to the date I was working on the patch, that should be updated to the actual version. Second step is to add library versioning (see https://autotools.io/libtool/version.html).

**Comment by davidanthoff** [comment]
It would also be great if a source tarball (``make dist``) would be uploaded for each tagged release. [This](https://docs.travis-ci.com/user/deployment/releases) might help.

**Comment by evanmiller** [comment]
We now have a system for versioned releases so I am closing this issue.
