### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by mes9** [WizardMac/ReadStat#30]
Hi, like many on here I apologize if this is a basic question, I'm new to this...
I'm trying to compile on Cygwin and I get the following error:

$ make
[ -x /usr/local/bin/ragel ] && /usr/local/bin/ragel src/readstat_por_parse.rl -G2
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 1

I assume it's because the makefile isn't tweaked. Can anyone help provide the makefile to compile it on windows?

**Comment by diogocp** [comment]
You will need to compile and install [ragel](https://www.colm.net/open-source/ragel/) and [libiconv](http://www.gnu.org/software/libiconv/). Then check diogocp/ReadStat@0f7c49eb61a44283aed72c6887e44e7210e3ad5c for a tweaked Makefile.

**Comment by evanmiller** [comment]
With #48 ReadStat uses ./configure to create the Makefile. Closing.
