### ISSUE TITLE
defining custom missingness conditions when writing to sav (and others?)

### ISSUE THREAD

**Issue by sjPlot** [WizardMac/ReadStat#31]
Just a reminder, see discussion / pos
ting [here](https://github.com/hadley/haven/issues/33#issuecomment-119508416). If it would be possible to do that, it's a nice feature to have.

**Comment by evanmiller** [comment]
Partially addressed here:

https://github.com/WizardMac/ReadStat/commit/8a6835d119025a2729bd2ffafb4a2463ec0687b8

A full solution will support SPSS's missing ranges feature.

**Comment by evanmiller** [comment]
More support here:

https://github.com/WizardMac/ReadStat/commit/3bf2eb464e2ae75b79f3fef17b0eb29790325af5

This should cover all use cases with the SAV format, so closing the issue.

**Comment by sjPlot** [comment]
Thanks a lot! :+1:
