### ISSUE TITLE
Fail to parse big-endian >2GB SAS files on Windows

### ISSUE THREAD

**Issue by evanmiller** [WizardMac/ReadStat#34]
See discussion here: https://github.com/WizardMac/ReadStat/issues/33

**Comment by evanmiller** [comment]
@vinhdizzo - Are you able to open a >2.1GB file on Windows that was created by SAS on a little-endian platform? It's possible this issue is limited to files created on big-endian platforms.

**Comment by vinhdizzo** [comment]
I don't have immediate access to SAS on a little-endian platform.  I may have an old Linux laptop with SAS installed...and can look for it.  Will have to roll the date back to see if that works.  Will take some time though.

**Comment by evanmiller** [comment]
Will, it's not urgent, just thought that might provide a clue. I believe others have had success with large files on Windows, so for now I'm going to guess this is a created-on-big-endian issue.

**Comment by vinhdizzo** [comment]
Created a > 2GB file on a little-endian platform and I was able to read it on Windows.  Thus, I think this issue is specific to > 2GB files created on a big-endian platform.

**Comment by evanmiller** [comment]
This is good to know. Can you try the same file on AIX and see which error you get? ("Cannot allocate vector" or "Invalid file, or file has unsupported features"). Please report the result in #33.

**Comment by evanmiller** [comment]
Does the >2.1 GB error happen immediately when you open on Windows?

**Comment by vinhdizzo** [comment]
Yes, immediately.

**Comment by evanmiller** [comment]
It's possible the AIX-related patches fixed this issue -- please try the latest ReadStat code and re-test.

Instructions for updating: https://github.com/hadley/haven#updating-readstat

**Comment by vinhdizzo** [comment]
I downloaded haven-master.zip and ReadStat-master.zip, extracted the 2, copied c and h files from ReadStat to haven, ran the unlink function in R, and used devtools to install the latest haven.  I get the following errors on a few files on windows:

```{r}
> d1 = read_sas('bar_big_endian.sas7bdat')
ReadStat: Failed to seek to position 2165189632 (= 8192 + 26765*80896)
ReadStat: Unable to seek within file (retval = 13): No error (errno = 0)

Error: Failed to parse bar_big_endian.sas7bdat: Unable to seek within file.
> d1 = read_sas('baz2gb.sas7bdat')
ReadStat: Failed to seek to position 2428101632 (= 8192 + 30015*80896)
ReadStat: Unable to seek within file (retval = 13): No error (errno = 0)

Error: Failed to parse baz2gb.sas7bdat: Unable to seek within file.
> d1 = read_sas('bar_little_endian.sas7bdat')
ReadStat: Failed to seek to position 2225861632 (= 8192 + 27515*80896)
ReadStat: Unable to seek within file (retval = 13): No error (errno = 0)

Error: Failed to parse bar_little_endian.sas7bdat: Unable to seek within file.
```

**Comment by evanmiller** [comment]
Thanks. Try this: [readstat_io.c](https://raw.githubusercontent.com/WizardMac/ReadStat/8c48d04adc2395202546cb7367dc985b22190f5a/src/readstat_io.c)

**Comment by vinhdizzo** [comment]
This is on Windows (replaced readstat_io.c with the merged haven-master and ReadStat-master).  Error compiling:
```{r}
gcc -m64 -I"F:/RRO/R-3.2.2/include" -DNDEBUG    -I"F:/RRO/R-3.2.2/library/Rcpp/include" -I"F:/RRO/R-3.2.2/library/BH/include" -I"c:/applications/extsoft/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c readstat_variable.c -o readstat_variable.o
gcc -m64 -I"F:/RRO/R-3.2.2/include" -DNDEBUG    -I"F:/RRO/R-3.2.2/library/Rcpp/include" -I"F:/RRO/R-3.2.2/library/BH/include" -I"c:/applications/extsoft/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c readstat_writer.c -o readstat_writer.o
g++ -m64 -shared -s -static-libgcc -o haven.dll tmp.def DfReader.o DfWriter.o RcppExports.o readstat_bits.o readstat_convert.o readstat_dta.o readstat_dta_read.o readstat_dta_write.o readstat_error.o readstat_io.o readstat_parser.o readstat_por.o readstat_por_parse.o readstat_sas.o readstat_sav.o readstat_sav_parse.o readstat_sav_read.o readstat_sav_write.o readstat_spss.o readstat_spss_parse.o readstat_value.o readstat_variable.o readstat_writer.o -lRiconv -Lc:/applications/extsoft/lib/x64 -Lc:/applications/extsoft/lib -LF:/RRO/R-3.2.2/bin/x64 -lR
readstat_por.o:readstat_por.c:(.text+0x41b): undefined reference to `ck_hash_table_init'
readstat_por.o:readstat_por.c:(.text+0x534): undefined reference to `ck_hash_table_free'
readstat_por.o:readstat_por.c:(.text+0x9d8): undefined reference to `ck_str_hash_lookup'
readstat_por.o:readstat_por.c:(.text+0xd82): undefined reference to `ck_str_hash_insert'
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'haven'
* removing 'F:/RRO/R-3.2.2/library/haven'
* restoring previous 'F:/RRO/R-3.2.2/library/haven'
Error: Command failed (1)
```

**Comment by evanmiller** [comment]
Do you see CKHashTable.c in the "src" directory?

**Comment by vinhdizzo** [comment]
No, I did not.  I must've deleted it while I deleted the .o and .dll files.  Just replaced it and am getting the following:
```{r}
> d1 = read_sas('bar_big_endian.sas7bdat')
ReadStat: Failed to seek to position 2165189632 (= 8192 + 26765*80896)
ReadStat: Unable to seek within file (retval = 13): No error (errno = 0)

Error: Failed to parse bar_big_endian.sas7bdat: Unable to seek within file.
> d1 = read_sas('baz2gb.sas7bdat')
ReadStat: Failed to seek to position 2428101632 (= 8192 + 30015*80896)
ReadStat: Unable to seek within file (retval = 13): No error (errno = 0)

Error: Failed to parse baz2gb.sas7bdat: Unable to seek within file.
> d1 = read_sas('bar_little_endian.sas7bdat')
ReadStat: Failed to seek to position 2225861632 (= 8192 + 27515*80896)
ReadStat: Unable to seek within file (retval = 13): No error (errno = 0)

Error: Failed to parse bar_little_endian.sas7bdat: Unable to seek within file.
```

**Comment by evanmiller** [comment]
Try this please: [readstat_io.c](https://github.com/WizardMac/ReadStat/blob/469c213434fdf5416f157dfba90fca3d0b02c346/src/readstat_io.c)

**Comment by vinhdizzo** [comment]
> d1 = read_sas('bar_big_endian.sas7bdat')
ReadStat: Failed to seek to position 2165189632 (= 8192 + 26765*80896)
ReadStat: Unable to seek within file (retval = 13): No error (errno = 0)

Error: Failed to parse bar_big_endian.sas7bdat: Unable to seek within file.
> d1 = read_sas('baz2gb.sas7bdat')
ReadStat: Failed to seek to position 2428101632 (= 8192 + 30015*80896)
ReadStat: Unable to seek within file (retval = 13): No error (errno = 0)

Error: Failed to parse baz2gb.sas7bdat: Unable to seek within file.
> d1 = read_sas('bar_little_endian.sas7bdat')
ReadStat: Failed to seek to position 2225861632 (= 8192 + 27515*80896)
ReadStat: Unable to seek within file (retval = 13): No error (errno = 0)

Error: Failed to parse bar_little_endian.sas7bdat: Unable to seek within file.

**Comment by evanmiller** [comment]
Are you sure you updated the file? You should see a message like "Calling _lseeki64 on a 64-bit number..."

**Comment by vinhdizzo** [comment]
Thought I did.
```{r}
> library(haven)
> d1 = read_sas('bar_big_endian.sas7bdat')
ReadStat: Failed to seek to end of file

ReadStat: Unable to seek within file (retval = 13): No error (errno = 0)

Error: Failed to parse bar_big_endian.sas7bdat: Unable to seek within file.
> d1 = read_sas('baz2gb.sas7bdat')
ReadStat: Failed to seek to end of file

ReadStat: Unable to seek within file (retval = 13): No error (errno = 0)

Error: Failed to parse baz2gb.sas7bdat: Unable to seek within file.
> d1 = read_sas('bar_little_endian.sas7bdat')
ReadStat: Failed to seek to end of file

ReadStat: Unable to seek within file (retval = 13): No error (errno = 0)

Error: Failed to parse bar_little_endian.sas7bdat: Unable to seek within file.
```

**Comment by evanmiller** [comment]
Try this: [readstat_io.c](https://github.com/WizardMac/ReadStat/commit/27e35f164bd44d131e85c91cd3d5d69732e40d99)

**Comment by vinhdizzo** [comment]
Bingo!
```{r}
> library(haven)
> d1 = read_sas('bar_big_endian.sas7bdat')
> dim(d1)
[1] 26750 10002
> d1 = read_sas('baz2gb.sas7bdat')
> dim(d1)
[1] 30000 10002
> d1 = read_sas('bar_little_endian.sas7bdat')
> dim(d1)
[1] 27500 10002
```
But, error for a file with 9704906752 bytes (errors out after a long while trying to load the data).
```{r}
> d1 = read_sas('combined_all.sas7bdat')
Error: Failed to parse combined_all.sas7bdat: A row in the file was not the expected length.
```

**Comment by evanmiller** [comment]
:+1:

Closing the issue. Please open a separate issue for the "A row in the file was not the expected length" error.

Thanks for all your cooperation with debugging these large-file issues -- many haven/ReadStat users will be happy to have this stuff work on Windows and UNIX servers.
