### ISSUE TITLE
SAS catalog: large value label sets not being imported

### ISSUE THREAD

**Issue by evanmiller** [WizardMac/ReadStat#39]
Very long variable labels are sometimes stored in SAS catalog files rather than the data file.

Technical note: they appear to be in blocks where `(lsp[8] & 0x80) == 0`

**Comment by gergness** [comment]
Sorry, I may have mixed-up terminology to confuse you. These are what's normally in the formats library (value labels?). So value `535` should be labelled `IA: NON-HISPANIC BLACK`.

**Comment by evanmiller** [comment]
Ah, okay, that makes more sense. In this context I call `IA: NON-HISPANIC BLACK` a value label.

Regardless -- you are seeing that value labels that are part of a large set aren't being imported, is that correct?

**Comment by gergness** [comment]
Exactly.

**Comment by evanmiller** [comment]
Notes for myself:

When a value label set can't fit on a single page, SAS writes the data across multiple pages, not necessarily in order. The continuation page does not have the usual block pointers. Information about whether a page is a primary page or a continuation page seems to appear in `lsp[8]` -- maybe in `0x80` -- but it's not clear how pages are connected together.

Two possibilities worth investigating:
* The first three catalog pages might contain some kind of index into the pages. (Does there appear to be some kind of table with the same # of records as # of pages in the file?)
* The pages themselves might be a linked list, containing a pointer to the next page. FileMaker Pro files work like this.

**Comment by evanmiller** [comment]
More notes for myself:

The blocks begin 6 bytes earlier than I suspected -- the first 6 bytes indicate whether the block has been deleted, and whether the block data is continued in another block. The first 4 bytes indicate the page with the block continuation (or -1 for a deleted block); the next 2 bytes contain the position within the page where the block continuation can be found. For most blocks, these are both 0. (This explains some "off by 6 bytes" errors in previous implementations.)

It also appears that the block payload length and block container length appear explicitly in the block header at `lsp[6]` and `lsp[14]`. The "chunk count" was something of a red herring, as that was just the MSB of the block container length.

I think I have enough information to read long label sets, though it's not clear how to identify a continuation block that is encountered in normal parsing and skip over it. One possibility is that the XLSR records in the first 3 pages appear to be some kind of index into the blocks, as they contain page numbers and positions within pages of the blocks. It's possible that these records also indicate which blocks are continuations.

**Comment by evanmiller** [comment]
Ok, I think I've cracked the nut with this commit:

https://github.com/WizardMac/ReadStat/commit/1d99928ad1d3c69e6a061ea98fae0973bfb75c6d

(Also includes some code reorganization so the commit is not really legible.)

@gergness Please update to the latest ReadStat/master code and see if all of your value labels are now imported as expected. Thanks!

**Comment by evanmiller** [comment]
@gergness the file you initially provided with the `STRATCF` variable is working for me now, and is correctly parsing e.g. `535 = IA: NON-HISPANIC BLACK`. Closing the issue.

If you experience other problems with the library, please open a new issue. Thanks!

**Comment by gergness** [comment]
Also fixed here, thanks!

**Comment by evanmiller** [comment]
Great, thanks for letting me know. The latest ReadStat code is now in haven/master so feel free to use that.
