### ISSUE TITLE
Generate error message from readstat_error_t

### ISSUE THREAD

**Issue by hadley** [WizardMac/ReadStat#4]
It would be useful if there was a function that turned the error code into a string for reporting messages to the user.

**Comment by hadley** [comment]
Oops, I guess that's `readstat_error_message()`!

**Comment by hadley** [comment]
Although it's a little weird that the parser functions return `int`, but `readstat_error_message()` needs a `readstat_error_t`

**Comment by hadley** [comment]
Also `readstat_error_message` doesn't appear to be defined anywhere

**Comment by evanmiller** [comment]
Oops, forgot to add readstat_error.c to the repository. Added:

https://github.com/WizardMac/ReadStat/commit/5b2271b4fa9ad84597592216809edc68557027bf

The parser functions should return readstat_error_t. I'll create a separate issue.
