### ISSUE TITLE
Value labels from SAS catalog files are mixed up

### ISSUE THREAD

**Issue by evanmiller** [WizardMac/ReadStat#40]
Sometimes value labels from SAS catalog files are off by 1, or completely out of order. For previous discussion see https://github.com/hadley/haven/issues/116 and https://github.com/WizardMac/ReadStat/issues/38

**Comment by evanmiller** [comment]
@gergness @jmurray1022 the label ordering issues should now be fixed in ReadStat master. Please test.

You may see some remaining issues in Haven with the treatment of multiple missing values. (They may get squished to a single missing value.) This will be treated as a separate bug in ReadStat, haven, or both.

**Comment by gergness** [comment]
Yep, fixed in my data. Thanks! 

As you suggested, the missings are squashed to be NaN in the value label definitions, and are NA in the dataset.

```
> head(data3$DRK6_3B)
<Labelled>
[1]  6 NA NA NA NA NA

Labels:
 value                    label is_na
     1 14 DRINKS OR MORE A WEEK FALSE
     2    7 TO 13 DRINKS A WEEK FALSE
     3     4 TO 6 DRINKS A WEEK FALSE
     4     1 TO 3 DRINKS A WEEK FALSE
     5 LESS THAN 1 DRINK A WEEK FALSE
     6       I DIDNT DRINK THEN FALSE
   NaN                 DK/BLANK FALSE
   NaN                     SKIP FALSE
```

![image](https://cloud.githubusercontent.com/assets/2104579/10432931/0ad57e98-70d4-11e5-9613-9143a6410f9d.png)

**Comment by evanmiller** [comment]
Great, glad it's in the right order at least. Closing the issue.

If you'd like better support for tagged missing values, please open an issue against haven. This may ultimately require changes to ReadStat, but there will need to be a discussion about how to represent these values in R.
