### ISSUE TITLE
Windows binaries

### ISSUE THREAD

**Issue by mwsohn** [WizardMac/ReadStat#47]
This is not an issue. I was just wondering if there is any Windows binaries that I an download.

Thanks

**Comment by evanmiller** [comment]
There are not.

**Comment by witwall** [comment]
Windows version can be download here,
http://alitrack.com/2016/08/11/readstat-%E5%85%8D%E8%B4%B9-sas-stata-spss%EF%BC%8Crdata%EF%BC%8Ccsv%E4%B9%8B%E9%97%B4%E4%BA%92%E8%BD%AC%E5%B7%A5%E5%85%B7/
