### ISSUE TITLE
How should I tweak the Makefile on Windows?

### ISSUE THREAD

**Issue by JessicaYK** [WizardMac/ReadStat#49]
Hello,

I am using Cygwin on Windows 7 to install and compile all the necessary files (installing ragel, for example) to compile ReadStat. However, I am not exactly sure how I should "tweak" the Makefile. Any advice will be very helpful!

Thanks

**Comment by evanmiller** [comment]
Hi, please see #48 -- we are working on an autotools based solution that should work with Windows. Try that branch and see if it works for you.
