### ISSUE TITLE
Feature request: parallelize sas7bdat import

### ISSUE THREAD

**Issue by treysp** [WizardMac/ReadStat#50]
Thanks so much for all your work on this library - it is extremely helpful for my work! 

I recently discovered a Spark package that parallelizes importation of SAS files with the Parso library (link below). I don't know if it's feasible to implement this approach in ReadStat, but some datasets only available from the government in sas7bdat format are huge and speedier import would be excellent. Unfortunately, I have no C skills to offer for assistance...

https://github.com/saurfang/spark-sas7bdat

**Comment by evanmiller** [comment]
Is Parso significantly faster than ReadStat? I'm disinclined to pursue parallelism for its own sake, particularly if the processing is I/O bound.

**Comment by treysp** [comment]
Understood - will do some testing and get back to you. Thanks!
