### ISSUE TITLE
Write SAS files

### ISSUE THREAD

**Issue by hadley** [WizardMac/ReadStat#52]
I have completely forgotten if we've talked about this before, but how hard would it be?

**Comment by evanmiller** [comment]
Getting a writer to roundtrip within ReadStat won't be *too* hard. The trouble is producing a file that SAS will accept -- there are many poorly understood fields in the SAS format. I have no idea how long they will all take to get right, particularly without a copy of SAS to test against.

**Comment by evanmiller** [comment]
Basic SAS writer is now in master, mainly in order to provide test coverage for the SAS reader. Will need field reports to determine if the files open properly with SAS.

**Comment by hadley** [comment]
I'll flag as experimental in haven but I'm sure people will be excited about it
