### ISSUE TITLE
SPSS can't open files by haven

### ISSUE THREAD

**Issue by rubenarslan** [WizardMac/ReadStat#53]
Even very basic ones

```
haven::write_sav(mtcars, "mtcars.sav")`
```

> GET 
>   FILE='mtcars.sav'. 
>  
> >Error.  Command name: GET FILE 
> >Invalid SPSS Statistics data file: mtcars.sav (DATA1204) 
> >Execution of this command stops. 
>  
> >Error # 1405 in column 8.  Text: mtcars.sav 
> >Error when attempting to get a data file. 
> DATASET NAME DataSet1 WINDOW=FRONT.

-----

> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.4 (El Capitan)

**Comment by evanmiller** [comment]
Possibly fixed here: https://github.com/WizardMac/ReadStat/commit/8ef4deca2ad366d137f971a0ae104a2cb04dc2a2

**Comment by evanmiller** [comment]
You can test the fix by downloading this library and:

```{bash}
./autogen.sh
./configure
make
./readstat /path/to/working.sav /path/to/new.sav
```

Then open "new.sav" in SPSS.

**Comment by rubenarslan** [comment]
This just to confirm that this works. Can try via haven too, if that helps. Would I just need to update readstat as @hadley lines out in the README?

**Comment by hadley** [comment]
@rubenarslan no, just install haven from github

**Comment by rubenarslan** [comment]
@hadley I've tried it, it now works fine, even with item + label values generated in R.
