### ISSUE TITLE
Support file-level compression in SAV files (i.e. ZSAV files)

### ISSUE THREAD

**Issue by evanmiller** [WizardMac/ReadStat#54]
Newer versions of SPSS allow writing files in "ZSAV" format, which looks a lot like SAV except that the data (rows) portion of the file is compressed.

**Comment by evanmiller** [comment]
Details on the SAV format's ZLIB compression container can be found on this page:

https://www.gnu.org/software/pspp/pspp-dev/html_node/Data-Record.html#Data-Record

**Comment by jandraor** [comment]
Has there been any progress on this issue?

**Comment by evanmiller** [comment]
ZSAV support is now complete with all tests passing.

```
$ readstat file.sav file.zsav # Compress an SAV file
$ readstat file.zsav
Format: SPSS compressed binary file (ZSAV)
...
```

Please try the feature out and open a new issue if you encounter any bugs. Thanks!
