### ISSUE TITLE
Fix Windows appveyor build

### ISSUE THREAD

**Issue by davidanthoff** [WizardMac/ReadStat#59]
Moving the discussion out of the closed PR #57.

The latest master actually build successfully on my local system with msys2, so this is probably just ta case of some missing package that we need to add via pacman.

When I build locally I also don't get the warning about ``-lz`` that shows up in the appveyor log, so trying to figure out what is missing for that might be the first step.

**Comment by evanmiller** [comment]
Sounds good. I made a test branch fix-windows-iconv to experiment with AppVeyor and alternate branches (and to see if a tweak to configure.ac would fix things). Doesn't seem to have kicked off a build... not sure why.

**Comment by davidanthoff** [comment]
Appveyor is sometimes slow... I'm also experimenting with a branch in my fork where I just spit out the list of installed pacman packages on appveyor, comparing that with my local list should do the trick, I hope...

**Comment by evanmiller** [comment]
Ok good to know.
