### ISSUE TITLE
Remove R data frame code

### ISSUE THREAD

**Issue by evanmiller** [WizardMac/ReadStat#77]
This is a heads-up to everyone that I am in the process of moving the R data frame code into its own project -- currently living at https://github.com/evanmiller/librdata.

As ReadStat has grown, there has been less and less shared code between the RData reader and all of the other readers, partly because the RData format is column-oriented, whereas the others are row-oriented. In addition, RData introduces extra dependencies like LZMA which complicates the build, and at the moment it is the only code not covered by the round-trip tests. So I think moving to its own project is for the best.

I will be committing the removal to master soon, so "Speak now or forever hold your peace".

**Comment by evanmiller** [comment]
Ok, the extraction seems to be successful. I've moved some more code from Wizard into [librdata](https://github.com/evanmiller/librdata), so that the library can now write RData files in addition to reading them.

With the removal of RData support from ReadStat, code coverage is now up to 82% and the AppVeyor configuration is simplified a bit. I'll leave this issue open for a few days to field any complaints etc but I'm confident this is the right move.

**Comment by davidanthoff** [comment]
For ReadStat.jl, I think the best way to handle this is to wait until you cut a 1.0 here, and then get the opensuse build to use that new version.
