### ISSUE TITLE
Run a fuzzer on ReadStat

### ISSUE THREAD

**Issue by evanmiller** [WizardMac/ReadStat#82]
ReadStat has a roundtrip test suite, but a proper fuzzer (such as [AFL](http://lcamtuf.coredump.cx/afl/)) will help catch crashes from mal-formed input.

Submitting a list of crash reports from a fuzzer would be a great first project for someone who wants to contribute to ReadStat :-)

**Comment by evanmiller** [comment]
We're starting to get reports from Google Autofuzz project. I've also manually run [libFuzzer](http://llvm.org/docs/LibFuzzer.html) over the various file formats and caught a number of bugs. Continuous integration would be nice, perhaps we'll join OSS-Fuzz one day!

**Comment by kcc** [comment]
You are welcome on oss-fuzz. 
If you've already used libFuzzer manually, the integration should require minimal effort.

**Comment by evanmiller** [comment]
@kcc I have added notes on using libFuzzer with ReadStat here:

https://github.com/WizardMac/ReadStat#fuzz-testing

If libFuzzer is present the Makefile now builds 7 format-specific fuzzing targets, and `./generate_corpus` will create a corpus from the test cases.
