### ISSUE TITLE
Does it work for very large files?

### ISSUE THREAD

**Issue by yassmarzou** [WizardMac/ReadStat#83]
I am trying to convert a 78 GB sas7bdat to csv. The csv file is created but its size is still 0 KB. Isn't the library supposed to read and write incrementally? Thanks.

**Comment by evanmiller** [comment]
It is incremental but SAS files can take a while to start. ReadStat must first locate and read in the global string table which can be large. Let it run for a while.

**Comment by yassmarzou** [comment]
Indeed, it worked after a while. I'm closing the issue.
Thank you.
