### ISSUE TITLE
Unable to convert string to the requested encoding

### ISSUE THREAD

**Issue by witwall** [WizardMac/ReadStat#85]
When convert sas7bdat created with SAS 9.4, I got this error message,

```
ReadStat: Error parsing page 0, bytes 262144-524287
Error processing test.sas7bdat: Unable to convert string to the requested encoding (invalid byte sequence)
```

[test.zip](https://github.com/WizardMac/ReadStat/files/523476/test.zip)

I tried other simple example, no problem.
[sas94.zip](https://github.com/WizardMac/ReadStat/files/523482/sas94.zip)

**Comment by evanmiller** [comment]
Hi, it looks like an issue with the 195th variable that begins with "柯"... do you see anything unusual about it when you open with SAS?

**Comment by witwall** [comment]
works fine with SAS 9.3 and 9.4, when convert to v7 version, open with 8.2 without issues.

after checked and tested variables begin with 柯， it would  get the issue when the variable was 柯妮丝麗.

<img width="148" alt="screen shot 2016-10-12 at 9 57 12 pm" src="https://cloud.githubusercontent.com/assets/3222056/19312988/6af216ec-90c7-11e6-9787-c70f61dda3cf.png">


[test.zip](https://github.com/WizardMac/ReadStat/files/524738/test.zip)

**Comment by witwall** [comment]
[haven](https://github.com/tidyverse/haven) works.

**Comment by FriedEgg** [comment]
I believe the issue is with the use of iconv encoding=EUC-CN by ReadStat.  It appears to me, that while SAS states using this encoding, it is actually using a newer version, such as GBK or GB18030.  In the example variable, for instance, the final character "麗" is not part of the EUC-CN character set.

**Comment by evanmiller** [comment]
Nice detective work, @FriedEgg. I will switch ReadStat to use a newer standard.

**Comment by FriedEgg** [comment]
thanks @evanmiller , this same item came up recently with epam/parso#11
