### ISSUE TITLE
Use of stderr

### ISSUE THREAD

**Issue by hadley** [WizardMac/ReadStat#89]
Unfortunately this isn't allowed in R.  It only seems to be used in one place (`readstat_sav_date_string()`) and I think this must be new.

**Comment by evanmiller** [comment]
Yeah this is part of some new code used by the CSV converter. FWIW I don't think this code is used by the main library at all so I'll see if I can move it.

**Comment by evanmiller** [comment]
Fixed in https://github.com/WizardMac/ReadStat/commit/e96a41b26918bbb209fbcf20a367cd0cf2817b35

**Comment by hadley** [comment]
Thanks!
