### ISSUE TITLE
Value wrappers

### ISSUE THREAD

**Issue by hadley** [WizardMac/ReadStat#9]
It would be convenient to have something like `readstat_value_char`, `readstat_value_string` etc... rather than having to do the casting yourself (that seems a little risky to me)

**Comment by evanmiller** [comment]
Agreed.

**Comment by evanmiller** [comment]
Added:

https://github.com/WizardMac/ReadStat/commit/764d863c8d0931cf3772ae7e05f77cbdfe8b4913
https://github.com/WizardMac/ReadStat/commit/f29e7897b8533b13657adbf86ae27246cd814a9c

**Comment by hadley** [comment]
Thanks!
