### ISSUE TITLE
Unable to convert string to the requested encoding (incomplete byte sequence)

### ISSUE THREAD

**Issue by witwall** [WizardMac/ReadStat#93]
```readstat.exe res1.sas7bdat```

```
Format: SAS data file (SAS7BDAT)
Columns: 13
Rows: 11
File label: RES1
Timestamp: 01 Jun 2027 19:33
File format version: 90401
```

```
readstat.exe res1.sas7bdat res1.csv
ReadStat: Error parsing page 0, bytes 65536-131071
Error processing res1.sas7bdat: Unable to convert string to the requested encoding (incomplete byte sequence)  
```                              
it really has broken multi-byte characters.

[res1.sas7bdat.zip](https://github.com/WizardMac/ReadStat/files/1040440/res1.sas7bdat.zip)

**Comment by evanmiller** [comment]
Hi, do you know what program generated this file?

**Comment by witwall** [comment]
SAS code with bug, for example,

```
data abc;
x="abc你好";
wrong=substr(x,1,4);
right=ktruncate(x,1,4);
run;
```

**Comment by evanmiller** [comment]
Thanks. I guess we could go ahead and accept all input that's been truncated like this. Try this:

https://github.com/WizardMac/ReadStat/commit/3edfeedbddf2aa5ad0e27b54e74f417f7a7b8685

BTW it looks like there's another bug which is shifting the timestamp by 10 years. I'd be curious if DATETIME fields are also shifted by 10 years.

**Comment by witwall** [comment]
still error,

```
ReadStat: Error converting string to specified encoding: abc?
ReadStat: Error parsing page 0, bytes 65536-131071
Error processing abc.sas7bdat: Unable to convert string to the requested encoding (invalid byte sequence)
```
please feel free to have a look,

[Iconv: EILSEQ with ASCII//IGNORE but not with ASCII//TRANSLIT//IGNORE
](https://stackoverflow.com/questions/9249628/iconv-eilseq-with-ascii-ignore-but-not-with-ascii-translit-ignore)

**Comment by evanmiller** [comment]
Hi,  can you provide the "abc" sample file?

iconv returns two kinds of errors, `EILSEQ` for an invalid sequence and `EINVAL` for an incomplete sequence. I'm comfortable accepting `EINVAL` for truncated data, but `EILSEQ` could indicate other kinds of errors (e.g. wrong character encoding). However in this case it may be that there's a an incomplete sequence followed by space padding, so it would help to have your test file.

**Comment by evanmiller** [comment]
Try this: https://github.com/WizardMac/ReadStat/commit/30200f0b743511e3d9b56bfd64ebc0ed0a8cbf6a

**Comment by witwall** [comment]
Great! works now.
btw, do you still need abc sample file?

**Comment by evanmiller** [comment]
If it's working now then I don't need the sample file! Cheers

**Comment by witwall** [comment]
still have issue, if the incomplete sequence is not at the end of the string.
```
ReadStat: Error converting string to specified encoding: 启迪Laq奇智奇思Hama早学?C41
ReadStat: Error parsing page 0, bytes 65536-131071
Error processing abc.sas7bdat: Unable to convert string to the requested encoding (invalid byte sequence) 
```
here is the example file, 
[abc.zip](https://github.com/WizardMac/ReadStat/files/1139289/abc.zip)

**Comment by evanmiller** [comment]
How was this file created?

**Comment by evanmiller** [comment]
Note that if you're using the C API, you can disable string conversion altogether with

```C
readstat_parser_t *parser = readstat_parser_init();
readstat_set_handler_character_encoding(parser, NULL);
```

Then your handlers can convert it however you like. I'm really not keen on dropping mal-formed byte sequences within a string since it likely indicates other errors.

**Comment by witwall** [comment]
substring first, then combine with other string

**Comment by witwall** [comment]
maybe give another option to let select -c( discard unconvertible characters), just like iconv

**Comment by evanmiller** [comment]
Adding this option will be a lot of work; unless there's a lot of mal-formed data like this in the wild then I don't think it will be worth the effort. Closing for now.

**Comment by witwall** [comment]
Got it.
