### ISSUE TITLE
sas7bdat.parso for R 3.4.1?

### ISSUE THREAD

**Issue by anniemorgan** [WizardMac/ReadStat#94]
Hi Matt,

Thanks for writing this package.  I tried installing it today to R 3.4.1 on Mac OS X, and the response was "package ‘sas7bdat.parso’ is not available (for R version 3.4.1)."  Do you plan to have a version that can be installed in the current version of R?

Thanks,
Morgan

**Comment by BioStatMatt** [comment]
Hi Morgan,

The sas7bdat.parso package is not part of CRAN. It must be installed from
github. However, I have not maintained it recently, and I'm not sure it
will work either. Unfortunately, I do not have plans to update the
sas7bdat.parso package. It's a wrapper for the parso Java library, and I'm
not very well studied in R-Java interface. I assume that you've tried the
'haven' package, or even the 'sas7bdat' package, right? Did these fail?

Regards,
Matt

**Comment by evanmiller** [comment]
Hi, this is the issue tracker for the ReadStat C library. Please conduct future conversations about  sas7bdat.parso on the sas7bdat.parso issue tracker: https://github.com/BioStatMatt/sas7bdat.parso/issues

Thanks

**Comment by anniemorgan** [comment]
Hi Matt,

Yep, I tried those.  However, we were able to solve the problem using a python module.  Thanks for the comments and info.

Morgan
