### ISSUE TITLE
Segmentation Fault (core dumped) when converting sas7bdat to csv.

### ISSUE THREAD

**Issue by tilwani** [WizardMac/ReadStat#96]
$ sudo readstat ssFile.sas7bdat ssFile.csv
Segmentation fault (core dumped)

I am getting the segmentation fault error when i try to convert a file named ssfile.sas7bdat kept in the same folder to ssfile.csv. Is there any particular reason or solution to this problem.

**Comment by evanmiller** [comment]
Hi, please provide a link to an example file and I will take a look.
