### ISSUE TITLE
Make code C89 compatible - suggestion

### ISSUE THREAD

**Issue by huapeng01016** [WizardMac/ReadStat#99]
I would like to use the library in a project which is compiled using Visual Studio 2005 (which supports C89 but not C99).
 
I would like to know if people are interested in the following changes. If there are enough interests, I will try to submit my changes (which are rather substantial) instead of maintaining a separate project myself. 

1. Make the code C89 compatible, mainly change the variable declaration and initialization placement.
2. Make compiling on Windows not relying on msys2 hence be able to compile it with Microsoft tools (Visual Studio 2005 and up). 
3. Be able to choose between ICU and iconv.

**Comment by evanmiller** [comment]
Hi @huapeng01016, thanks for opening an issue about this.

I could foresee there being interest in items 2 & 3, but maintaining the project as C89 seems a bit draconian. Can you give me an idea of how many lines of code need to be changed?
